/*
******************************

Code to verify properties of Monster type axial algebras with the X(5) axet

******************************
*/
AttachSpec("../2-gen Monster.spec");
AttachSpec("../../AxialTools/AxialTools.spec");

QQ := Rationals();
// =========================================================
//
// 5A(al, (5al-1)/8)
//
// =========================================================

A, gen, frob := M5A();
F<al> := BaseRing(A);
bt := (5*al-1)/8;

assert al-bt eq (3*al+1)/8;
// al can't be -1/3 as then al = bt

// Check general properties

u0_1 := 3*bt*A.1 - 2*(A.3+A.4) -bt/(al-bt)*A.6;
u0_2 := (A.2+A.5) - (A.3+A.4) -bt/(al-bt)*A.6;

v_al := A.2+A.5-(A.3+A.4) +A.6;

w_bt_1 := A.2-A.5;
w_bt_2 := A.3-A.4;

assert u0_1*A.1 eq A!0;
assert u0_2*A.1 eq A!0;

assert v_al*A.1 eq al*v_al;

assert w_bt_1*A.1 eq bt*w_bt_1;
assert w_bt_2*A.1 eq bt*w_bt_2;

// Identity
so, id := HasOne(A);
assert so;
assert id eq 1/5/(al-bt)*A![1,1,1,1,1,0];
// So the algebra always has an identity if the characteristic is not 5

// No subalgebras to check
// See below in idempotents for additional automorphism

// ---------------------------------------------------
//
//     Ideals
//
// ---------------------------------------------------

assert frob[1,2] eq 3/4*bt;
// So the projection graph always has an edge between a_0 and a_1 since bt ne 0

assert Determinant(frob) eq -5^6/2^23*(al-bt)^2*(3*al-7)^5/bt;
// Since al \neq bt and the characteristic can't be 2
// the only possibilities are if the characteristic is 5, or al = 7/3

// We deal with al = 7/3, char not 5 below.

// See bottom for proof that 5A \cong IY_5 in char 5.
// Look in IY5 file for char 5 case.
// NB value of al makes no difference.

// ---------------------------------------------------
//
// Ideals for al = 7/3
//
// ---------------------------------------------------
A, gen, frob := M5A(7/3);

// The radical is 5-dimensional
assert Dimension(NullSpace(frob)) eq 5;
P<t> := PolynomialRing(QQ);
p := CharacteristicPolynomial(frob);
assert p eq t^5*(t-5);
// so the nullspace is 5-dimensional in any characteristic

R := ideal<A| [A!x : x in Basis(Nullspace(frob))]>;

u1 := A.1-A.5;
u2 := A.2-A.5;
u3 := A.3-A.5;
u4 := A.4-A.5;
u5 := A.6;
assert u1 in R and u2 in R and u3 in R and u4 in R and u5 in R;

// In ordinary representation theory, R has G-module structure 1+4, so just need to check the trivial submodule and the irreducible module generated by the difference of axes

assert Dimension(ideal<A | u1>) eq 5;
assert A.2*u1 eq 4/3*u1 + 2/3*u5;

assert Dimension(ideal<A | u5>) eq 5;
assert A.1*u5 eq u2-u3-u4+u5;
// So no subideals of R


//------------------------------------------
//
// Idempotents
//
//------------------------------------------
load "Find idempotents.m";

A, gen, frob := M5A();
F<al> := BaseRing(A);
bt := (5*al-1)/8;

t1 := MiyamotoInvolution(A.1);
t2 := MiyamotoInvolution(A.2);

phi := Matrix(F,[[ 1,0,0,0,0,0],
               [ 0,0,1,0,0,0],
               [ 0,0,0,0,1,0],
               [ 0,1,0,0,0,0],
               [ 0,0,0,1,0,0],
               [ 0,0,0,0,0,-1]]);


// phi is an automorphism
assert forall{ <i,j> : i,j in [1..6] | (A.i*phi)*(A.j*phi) eq (A.i*A.j)*phi};
Miy := sub<GL(6,F) | t1,t2>;
G := sub<GL(6,F) | t1,t2,phi>;

// Needed to ensure Magma knows the order of the group over FCl and so to be able to take orbits
assert Order(Miy) eq 10;
assert Order(G) eq 20;

//------------------------------------------
//
// Identify the singular points

// takes ~20 secs
II := IdealOfSingularPoints(A);
P := Generic(II);

// NB RadicalDecomposition is very slow.
// tried this and left for a couple of days and it didn't finish

// takes ~400 seconds
prim := ProbableRadicalDecomposition(II);
assert #prim eq 13;

// alpha can't be 1, or 1/5 (al=1/5 gives bt = 0)
poss := [ J : J in prim | P.7-1 notin J and P.7-1/5 notin J];
assert forall{ J : J in poss | IsPrime(J) };

assert #poss eq 10;

// For al = 1/2, axes and id-axes are singular
Jaxes := [ ideal<P | [ P.j : j in [1..5] | j ne i] cat [P.i-1,P.6, P.7-1/2]> : i in [1..5]];
Jaxes_id := [ ideal<P | [ P.j -16/25 : j in [1..5] | j ne i] cat [P.i+9/25,P.6, P.7-1/2]> : i in [1..5]];

assert forall{ J : J in Jaxes cat Jaxes_id | J in poss };

// Idempotents in the generic case

I := IdempotentIdeal(A);

// Takes about 13 secs
prim := PrimaryDecomposition(I);

FCl := AlgebraicClosure(F);
// Need to add roots
// bt = (5*al-1)/8;

// NB al \neq 0, 1/5
f := al^3-6*al^2+1;
rt1 := Sqrt(FCl!(-5*8*bt/(3*al-7)));
rt2 := Sqrt(FCl!5/al);
rt3 := Sqrt(FCl!(2*al-1));
rt4 := Sqrt(FCl!-8*bt/(al^3-6*al^2+1));

// So bad points are al = 1/2, 7/3 and roots of f
ACl := ChangeRing(A, FCl);
frobCl := ChangeRing(frob, FCl);

vars := [ Variety(J, FCl) : J in prim];

idems := &cat[ [ ACl![ t[i] : i in [1..6]] : t in var] : var in vars];

// Simplify takes a long time, but partial is quick
Simplify(FCl:Partial:=true);
Prune(FCl);

G_FCl := ChangeRing(G, FCl);
orbs := {@ {@ ACl!u : u in Orbit(G_FCl, Vector(v))@} : v in idems @};
Sort(~orbs, func<x,y|#x-#y>); // sort smallest first

assert #orbs eq 10;
assert [#o : o in orbs] eq [ 1, 1, 2, 5, 5, 10, 10, 10, 10, 10];

function len(v)
  return InnerProduct(v*frobCl, v);
end function;

// zero and the identity are the two idempotents in an orbit of size one.
so, id := HasOne(ACl);
assert so;
assert id eq 8/(5*(3*al+1))*ACl![1,1,1,1,1,0];
assert len(id) eq 2^3/(3*al + 1);


v1 := 1/10/(al-bt)*rt1*ACl.6;
assert id/2 + v1 in orbs[3];
assert id/2 - v1 in orbs[3];
assert len(id/2 + v1) eq 2^2/(3*al + 1);
assert len(id/2 - v1) eq 1/2/(al-bt);

// The fusion law has four eigenvalues and is not graded
evals, espaces, FL := IdentifyFusionLaw(id/2 + v1);
GR, gr := Grading(FL);
assert Order(GR) eq 1;
assert #evals eq 4;

// for the orbits of size 5 we have the axes and id - axes
assert {@ ACl.i : i in [1..5] @} in orbs;
assert {@ id - ACl.i : i in [1..5] @} in orbs;
assert len(id-ACl.1) eq (7-3*al)/(3*al + 1);
assert len(id-ACl.1) eq (7-3*al)/(al-bt)/8;

// One of the orbits of size 10
v2 := 1/5/al*rt1*( ACl.2+ACl.5 - (ACl.3+ACl.4) + (al-1)/8/(bt-al)*ACl.6);

assert exists(o2){ o : o in orbs | id/2 + v2 in o};
assert id/2 - v2 in o2;
assert len(id/2 - v2) eq 2^2/(3*al + 1);
assert len(id/2 + v2) eq 2^2/(3*al + 1);

evals, espaces, FL := IdentifyFusionLaw(id/2 + v2);
assert #evals eq 6;
GR, gr := Grading(FL);
assert Order(GR) eq 2;
assert MiyamotoInvolution(v2) eq t1;

// id-v2 is equal to the above but with the last big sum as a minus
phi_FCl := ChangeRing(phi, FCl);
assert v2*phi_FCl eq -v2;
// So the extra automorphism is related to a field automorphism exchanging rt1 for -rt1


// Two more orbits of size 10
v3 := ACl.1/2
           + rt2/10*( ACl.2+ACl.5 - (ACl.3+ACl.4) + bt/(bt-al)*ACl.6);

assert exists(o3){ o : o in orbs | id/2 + v3 in o};
assert id/2 -v3 notin o3;
assert len(id/2 + v3) eq (1 + (al -bt)) /2/(al-bt);

evals, espaces, FL := IdentifyFusionLaw(id/2 + v3);
assert #evals eq 5;
GR, gr := Grading(FL);
assert Order(GR) eq 2;
assert MiyamotoInvolution(id/2 + v3) eq t1;

assert exists(o3_pair){ o : o in orbs | id/2-v3 in o};
assert len(id/2-v3) eq (1 - (al -bt)) /2/(al-bt);

// The extra automorphism is related to a field automorphism exchanging rt2 for -rt2
assert (v3 - ACl.1/2)*phi_FCl eq -(v3 -ACl.1/2);

// One of id/2+v3 and id/2-v3 is primitve and the other is not
assert {Dimension(Eigenspace(x, 1)) : x in [id/2+v3, id/2-v3]} eq {1,2};
assert exists(x){ x : x in [id/2+v3, id/2-v3] | Dimension(Eigenspace(x, 1)) eq 1};

// We have
assert x + x*phi_FCl eq id - ACl.1;

// Final two orbits of size 10
v4 := rt4/5* ( 1/16*(7*al+5)/(bt-al)*ACl.1  - al/2/(bt-al)*(ACl.2+ACl.3+ACl.4+ACl.5)
                          + 1/2*rt2*rt3*( ACl.2 + ACl.5 - (ACl.3+ACl.4) + ACl.6));
         
assert exists(o4){ o : o in orbs | id/2 + v4 in o};
assert id/2 -v4 notin o4;
assert len(id/2 + v4) eq (1+bt*rt4)/2/(al-bt);

evals, espaces, FL := IdentifyFusionLaw(id/2 + v4);
assert #evals eq 6;
GR, gr := Grading(FL);
assert Order(GR) eq 2;
assert MiyamotoInvolution(id/2 + v4) eq t1;

assert exists(o4_pair){ o : o in orbs | id/2-v4 in o};
assert len(id/2-v4) eq (1-bt*rt4)/2/(al-bt);

// The extra automorphism is related to a field automorphism fixing rt4
assert v4*phi_FCl + v4 eq
           2* ( rt4/5* ( -1/16*(7*al+5)/(al-bt)*ACl.1 + al/2/(al-bt)*(ACl.2+ACl.3+ACl.4+ACl.5) ));

// And also fixing rt3.
assert v4*phi_FCl - v4 eq
           -2* ( rt4/5*1/2*rt2*rt3*( ACl.2 + ACl.5 - (ACl.3+ACl.4) + ACl.6) );

// So the extra automorphism phi seems to be related to a field automorphism which inverts rt1 and rt2 and fixes rt3 and rt4.  Perhaps related to sqrt(5)??

// We have found all the remaining axes
assert #(o2 join o3 join o3_pair join o4 join o4_pair) eq 50;

// -----------------------------
//
// Check for new axes

poss := FindMatchingIdempotents(ACl.1, orbs);

assert #poss eq 3;

P<t> := PolynomialRing(F);
p := CharacteristicPolynomial(AdjointMatrix(ACl.1)) - poss[1,2];
assert p eq (1-al)/2*t*(9*t^4 - 45/2*t^3 + (25*al^2 - 90*al + 369)/2^4*t^2 -3*(25*al^2 - 90*al + 129)/2^5*t + (5*al - 9)^2/2^5);
// al neq 1

p := CharacteristicPolynomial(AdjointMatrix(ACl.1)) - poss[3,2];
assert p eq (al-1)/2^2*t*( (173*al^3 - 387*al^2 + 175*al - 25)/2^3/al^2/(3*al - 7)^2 
                       + (225*al^6 - 915*al^5 + 739*al^4 - 1042*al^3 + 3779*al^2 - 1475*al + 225)/2^4/al^2/(3*al - 7)^2*t
                       - (75*al^5 + 185*al^4 - 555*al^3 - 1171*al^2 + 300*al - 50)/2^4/al^2/(3*al - 7)*t^2
                       + (315*al^4 - 66*al^3 - 1814*al^2 + 150*al - 25)/2^4/al^2/(3*al - 7)*t^3
                       - 3^2*t^4);
// al ne 1

p := CharacteristicPolynomial(AdjointMatrix(ACl.1)) - poss[2,2];
assert p eq (9*al-5)/8*t^2*( -3*t^3 + (35*al^2 + 146*al - 5)/2^5/al*t^2 -(25*al^3 + 55*al^2 + 127*al - 15)/2^6/al*t + (5*al - 1)*(5*al^2 - 2*al + 5)/2^6/al);
assert poss[2,1] in o3_pair join o3;
// al = 5/9 is possible - need to check!!

// Checking 
al := 5/9;
bt := (5*al-1)/8;
assert bt eq 2/9;

A, gens, frob := M5A(al);

// For v3, we need the root of 5/al, but this is now sqrt{9}
assert 5/al eq 9;
rt2 := 3;

so, id := HasOne(A);
assert so;

v3 := A.1/2
           + rt2/10*( A.2+A.5 - (A.3+A.4) + bt/(bt-al)*A.6);

// pick the correct one
assert exists(x){ x : x in [id/2+v3, id/2-v3] | CharacteristicPolynomial(A.1) eq CharacteristicPolynomial(x)};

assert HasMonsterFusionLaw(x: fusion_values:=[5/9, 2/9]);
assert InnerProduct(x*frob, x) eq 1;

mymod := function(i,n)                                              
  if i mod n eq 0 then
    return n;
  else
    return i mod n;
  end if;
end function;

xi := function(i)
  return 1/5*(-A.i + 3*A.mymod(i+2,5) + 3*A.mymod(i+3,5) +A.6);        
end function;

xip := function(i);
  return 1/5*(-A.i + 3*A.mymod(i+1,5) + 3*A.mymod(i+4,5) -A.6);
end function;

ox := {@ xi(i) : i in [1..5] @} join {@ xip(i) : i in [1..5] @};

t1 := MiyamotoInvolution(A.1);
phi := Matrix(Rationals(),[[ 1,0,0,0,0,0],
               [ 0,0,1,0,0,0],
               [ 0,0,0,0,1,0],
               [ 0,1,0,0,0,0],
               [ 0,0,0,1,0,0],
               [ 0,0,0,0,0,-1]]);


// phi is an automorphism
assert forall{ <i,j> : i,j in [1..6] | (A.i*phi)*(A.j*phi) eq (A.i*A.j)*phi};
Miy := sub<GL(6,F) | t1,t2>;
G := sub<GL(6,F) | t1,t2,phi>;

assert ox eq {@ A!y : y in Orbit(G, Vector(x)) @};
assert #ox eq 10;

// So we have 5+10 = 15 axes in total.

assert (A.1 - xi(4))*xi(3) eq bt*(A.1 - xi(4));
// so tau_{x_2} swaps a_0 and x_3
// indexing to start at 0, not 1

assert (A.2 - xip(4))*xi(1) eq bt*(A.2 - xip(4));
assert (A.3 - xi(5))*xi(1) eq bt*(A.3 - xi(5));
// so \tau_{x_0} switches a_1 and x_3' and and switches a_2 and x_4
// indexing to start at 0, not 1

// This is enough to give a theoretical proof that Aut = S_5 and Miy = A5

ox_Miy := [ MiyamotoInvolution(y) : y in ox];

Miybar := sub<GL(6,QQ) | [t1, t2] cat ox_Miy>;

assert GroupName(Miybar) eq "A5";

GG := sub<GL(6,QQ) | [t1, phi] cat ox_Miy>;
assert GroupName(GG) eq "S5";

// This is a 3A subalgebra
B := sub<A | A.1, xi(3)>;
assert Dimension(B) eq 4;
assert xi(4) in B;


// ---------------------------------------------
//
// al = 1/2

al := 1/2;
bt := (5*al-1)/8;

A, gen, frob := M5A(al);
F := QQ;

t1 := MiyamotoInvolution(A.1);
t2 := MiyamotoInvolution(A.2);

phi := Matrix(F,[[ 1,0,0,0,0,0],
               [ 0,0,1,0,0,0],
               [ 0,0,0,0,1,0],
               [ 0,1,0,0,0,0],
               [ 0,0,0,1,0,0],
               [ 0,0,0,0,0,-1]]);


// phi is an auphitomorphism
assert forall{ <i,j> : i,j in [1..6] | (A.i*phi)*(A.j*phi) eq (A.i*A.j)*phi};
Miy := sub<GL(6,F) | t1,t2>;
G := sub<GL(6,F) | t1,t2,phi>;

// Needed to ensure Magma knows the order of the group over FCl and so to be able to take orbits
assert Order(Miy) eq 10;
assert Order(G) eq 20;

I := IdempotentIdeal(A);
prim := RadicalDecomposition(I);

FCl := AlgebraicClosure(F);

// No rt3
f := (al^3-6*al^2+1);
rt1 := Sqrt(FCl!(5*(1-5*al)/(3*al-7)));
rt2 := Sqrt(FCl!5/al);
rt4 := Sqrt(FCl!(1-5*al)/(al^3-6*al^2+1));

ACl := ChangeRing(A, FCl);
frobCl := ChangeRing(frob, FCl);

vars := [ Variety(J, FCl) : J in prim];
idems := &cat[ [ ACl![ t[i] : i in [1..6]] : t in var] : var in vars];

// We have all the idempotents above except for id/2 \pm v3 which isn't defined as it needs rt3
assert #idems eq 44;

Simplify(FCl:Partial:=true);
Prune(FCl);

G_FCl := ChangeRing(G, FCl);
orbs := {@ {@ ACl!u : u in Orbit(G_FCl, Vector(v))@} : v in idems @};
Sort(~orbs, func<x,y|#x-#y>); // sort smallest first

assert #orbs eq 8;
assert {*#o : o in orbs *} eq {* 1^^2, 2, 5^^2, 10^^3 *};

// zero and the identity are the two idempotents in an orbit of size one.
so, id := HasOne(ACl);
assert so;
assert id eq 8/(5*(3*al+1))*ACl![1,1,1,1,1,0];

v1 := 1/10/(al-bt)*rt1*ACl.6;
assert id/2 + v1 in orbs[3];
assert id/2 - v1 in orbs[3];

// One of the orbits of size 10
v2 := 1/5/al*rt1*( ACl.2+ACl.5 - (ACl.3+ACl.4) + (al-1)/8/(bt-al)*ACl.6);

assert exists(o2){ o : o in orbs | id/2 + v2 in o};
assert id/2 -v2 in o2;

// Two more orbits of size 10
v3 := ACl.1/2
           + rt2/10*( ACl.2+ACl.5 - (ACl.3+ACl.4) + bt/(bt-al)*ACl.6);

assert exists(o3){ o : o in orbs | id/2 + v3 in o};
assert id/2 -v3 notin o3;
assert exists(o3_pair){ o : o in orbs | id/2-v3 in o};

// --------------
//
// Double check for new axes

poss := FindMatchingIdempotents(ACl.1, orbs);
assert #poss eq 0;

// --------------------------------
//
// al = 7/3

al := 7/3;
bt := (5*al-1)/8;

A, gen, frob := M5A(al);
F := QQ;

I := IdempotentIdeal(A);
prim := RadicalDecomposition(I);

FCl := AlgebraicClosure(F);
// Need to add roots

f := (al^3-6*al^2+1);
rt2 := Sqrt(FCl!5/al);
rt3 := Sqrt(FCl!(2*al-1));
rt4 := Sqrt(FCl!(1-5*al)/(al^3-6*al^2+1));

ACl := ChangeRing(A, FCl);
frobCl := ChangeRing(frob, FCl);

vars := [ Variety(J, FCl) : J in prim];
idems := &cat[ [ ACl![ t[i] : i in [1..6]] : t in var] : var in vars];

Simplify(FCl:Partial:=true);
Prune(FCl);

G_FCl := ChangeRing(G, FCl);
orbs := {@ {@ ACl!u : u in Orbit(G_FCl, Vector(v))@} : v in idems @};
Sort(~orbs, func<x,y|#x-#y>); // sort smallest first

assert #orbs eq 8;
assert {*#o : o in orbs *} eq {* 1^^2, 5^^2, 10^^4 *};

// zero and the identity are the two idempotents in an orbit of size one.
so, id := HasOne(ACl);
assert so;
assert id eq 8/(5*(3*al+1))*ACl![1,1,1,1,1,0];


// Two more orbits of size 10
v3 := ACl.1/2
           + rt2/10*( ACl.2+ACl.5 - (ACl.3+ACl.4) + bt/(bt-al)*ACl.6);

assert exists(o3){ o : o in orbs | id/2 + v3 in o};
assert id/2 -v3 notin o3;
assert exists(o3_pair){ o : o in orbs | id/2-v3 in o};

v4 := rt4/5* ( 1/16*(7*al+5)/(bt-al)*ACl.1  - al/2/(bt-al)*(ACl.2+ACl.3+ACl.4+ACl.5)
                          + 1/2*rt2*rt3*( ACl.2 + ACl.5 - (ACl.3+ACl.4) + ACl.6));
         
assert exists(o4){ o : o in orbs | id/2 + v4 in o};
assert id/2 -v4 notin o4;
assert exists(o4_pair){ o : o in orbs | id/2-v4 in o};

assert #{ o3, o3_pair, o4, o4_pair} eq 4;

// --------------
//
// Double check for new axes

poss := FindMatchingIdempotents(ACl.1, orbs);
assert #poss eq 2;

P<t> := PolynomialRing(F);
p := CharacteristicPolynomial(AdjointMatrix(ACl.1)) - poss[1,2];
assert p eq 11/2^3/7*t*( 3^2*5^2*17/2^9 -13*19927/2^9/3^3*t + 419/3^3*t^2 - 17/2^2*t^3);
// This is not 0 (maybe issue in char 11)

p := CharacteristicPolynomial(AdjointMatrix(ACl.1)) - poss[2,2];
assert p eq 11/2^3/7*t*( 3^2*5^2*17/2^9 -13*19927/2^9/3^3*t + 419/3^3*t^2 - 17/2^2*t^3);
assert p eq 2*t^2*( 2^2*31/3^2/7 -379/3^2/7*t + 2^2*37/3/7*t^2 -3*t^3);
// char ne 2, so no issue

// --------------------------------
//
// al = root of f

P<t> := PolynomialRing(QQ);
f := t^3-6*t^2+1;
// The roots of f are distinct
assert Discriminant(f) eq 3^3*31;

A1, gen1, frob1 := M5A();
F<al> := BaseRing(A1);

FCl := AlgebraicClosure(F);
roots := Roots(f, FCl);

for r in roots do
  al := r[1];
  bt := (5*al-1)/8;
  
  phi := hom<F-> FCl | [al]>;
  
  A := ChangeRing(A1, FCl, phi);
  frob := ChangeRing(frob1, FCl, phi);
  
  // the rt4 from above isn't defined, but we need the others
  // Need to add roots

  rt1 := Sqrt(FCl!(5*(1-5*al)/(3*al-7)));
  rt2 := Sqrt(FCl!5/al);
  rt3 := Sqrt(FCl!(2*al-1));

  Simplify(FCl:Partial:=true);
  Prune(FCl);

  I := IdempotentIdeal(A);
  prim := RadicalDecomposition(I);
  
  ACl := ChangeRing(A, FCl);
  frobCl := ChangeRing(frob, FCl);

  vars := [ Variety(J, FCl) : J in prim];
  idems := &cat[ [ ACl![ t[i] : i in [1..6]] : t in var] : var in vars];

  G_FCl := ChangeRing(G, FCl);
  orbs := {@ {@ ACl!u : u in Orbit(G_FCl, Vector(v))@} : v in idems @};
  Sort(~orbs, func<x,y|#x-#y>); // sort smallest first

  assert #orbs eq 8;
  assert {*#o : o in orbs *} eq {* 1^^2, 2, 5^^2, 10^^3 *};

  // zero and the identity are the two idempotents in an orbit of size one.
  so, id := HasOne(ACl);
  assert so;
  assert id eq 8/(5*(3*al+1))*ACl![1,1,1,1,1,0];

  v1 := 1/10/(al-bt)*rt1*ACl.6;
  assert id/2 + v1 in orbs[3];
  assert id/2 - v1 in orbs[3];

  // One of the orbits of size 10
  v2 := 1/5/al*rt1*( ACl.2+ACl.5 - (ACl.3+ACl.4) + (al-1)/8/(bt-al)*ACl.6);

  assert exists(o2){ o : o in orbs | id/2 + v2 in o};
  assert id/2 -v2 in o2;

  // Two more orbits of size 10
  v3 := ACl.1/2
             + rt2/10*( ACl.2+ACl.5 - (ACl.3+ACl.4) + bt/(bt-al)*ACl.6);

  assert exists(o3){ o : o in orbs | id/2 + v3 in o};
  assert id/2 -v3 notin o3;
  assert exists(o3_pair){ o : o in orbs | id/2-v3 in o};

  assert #{o2, o3, o3_pair} eq 3;
  
  P<t> := PolynomialRing(FCl);
  poss := FindMatchingIdempotents(ACl.1, orbs);
  
  polys := [ CharacteristicPolynomial(AdjointMatrix(ACl.1)) - CharacteristicPolynomial(AdjointMatrix(o[1])) : o in orbs | ACl!0 notin o and ACl.1 notin o];
  assert forall{ p : p in polys | not IsZero(p)};
end for;



//-------------------------------------------------------------------------

// Theorem: IY5 and M5A are isomorphic in characteristic 5

A, gen, frob := M5A(: base_ring := GF(5));

AY := V2(: base_ring := GF(5));

// Checking the 6th basis vector

assert AY.6 eq AY.1*AY.2 - 3*(AY.1+AY.2);

// So set
v := A.1*A.2 - 3*(A.1+A.2);

bas := [ A.i : i in [1..5]] cat [v];
AA  := ChangeBasis(A, bas);

// Checking if the multiplication is the same

multA := [[Eltseq(v): v in R]: R in BasisProducts(AA)];
multAY := [[Eltseq(v): v in R]: R in BasisProducts(AY)];

assert multA eq multAY;
/////////////////////////////////////////////////////////

// Translate the ideals for IY5 into basis for 5A
R := ideal<A| [A!x : x in Basis(Nullspace(frob))]>;

u1 := AY![1,-1,0,0,0,0];
u2 := AY![1,-2,1,0,0,0];
u3 := AY![1,-3,3,-1,0,0];
u4 := AY![1,-4,6,-4,1,0];
z := AY.6;

CoB := Matrix(bas);

uu1 := A!Eltseq(u1*CoB);
uu2 := A!Eltseq(u2*CoB);
uu3 := A!Eltseq(u3*CoB);
uu4 := A!Eltseq(u4*CoB);
zz := A!Eltseq(z*CoB);

Ann := Annihilator(A);
assert uu4 in Ann;
assert Dimension(Ann) eq 1;

I3 := ideal<A| uu3>;
assert Dimension(I3) eq 2;
assert uu4 in I3;

x := uu2 - zz;
Ix := ideal<A | x>;
assert Dimension(Ix) eq 3;
assert x in Ix and uu3 in Ix and uu4 in Ix;

y := uu2 + 1/(2*al-1)*zz;
assert A.2*y eq 0;
Iy := ideal<A | y>;
assert Dimension(Iy) eq 3;
assert y in Iy and uu3 in Iy and uu4 in Iy;

I2 := ideal<A| uu2>;
assert Dimension(I2) eq 4;
assert uu3 in I2 and uu4 in I2;


