/*

Check the algebras which normally have the infinite axet

*/
AttachSpec("../2-gen Monster.spec");
AttachSpec("../../AxialTools/AxialTools.spec");

Attach("../Yabe_algebras.m");

load "Find idempotents.m";
QQ := Rationals();
// =========================================================
//
// IY3
//
// =========================================================

// The matrix [[1,mu],[mu,1]] has rank drop iff mu = pm 1.  This gives a non-trivial radical to the resulting algebra.
// This algebra should be simple provided al ne -1,2 and mu ne \pm 1

//////////////////////////////
// First case, if mu = 1
// This is the exceptional algebra
F<al> := FunctionField(QQ);
A, gens, frob := IY3(al,1);

_, _, FL := IdentifyFusionLaw(A.1: eigenvalues:=[1,0,al,1/2]);
Gr, gr := Grading(FL);
assert Order(Gr) eq Infinity();
assert NumberOfGenerators(Gr) eq 1;
assert IsAbelian(Gr);
// So the axes here are Z-graded
assert 2@gr eq 2*Gr.1;
assert 3@gr eq 2*Gr.1;
assert 4@gr eq Gr.1;
// But we can use a C_2-grading

null := NullSpace(frob);
assert Dimension(null) eq 3;
R := ideal<A | [A!v : v in Basis(null)]>;

assert A.1-A.2+A.3-2*A.4 in R and A.3 in R and A.4 in R;
assert A.1*(A.1-A.2+A.3-2*A.4) eq 1/2*(A.1-A.2+A.3-2*A.4);
// These vectors span the bt-, al-, 0-eigenspaces for A.1.  So these and their sums are the only candidates for ideals.

I0 := ideal<A | A.4>;
assert I0 eq Annihilator(A);
assert Dimension(I0) eq 1;

Q0, pi := quo<A | I0>;

assert A.1@pi eq Q0.1 and A.2@pi eq Q0.2;
assert Q0.1*Q0.2 eq 1/2*(Q0.1+Q0.2) + (al-1/2)*Q0.3;
assert Q0.1*Q0.3 eq al*Q0.3;
assert Q0.2*Q0.3 eq al*Q0.3;
assert Q0.3*Q0.3 eq Q0!0;
// This is Maddy Whybrow's example in fusion law (a), with bt = 1/2, x = 1 in
// Graded 2-generated axial algebras, https://arxiv.org/abs/2005.03577
assert Q0.1*(Q0.1*Q0.2) eq (al-1)*(1/2-1)*Q0.1 -al/2*Q0.2 +(al+1/2)*Q0.1*Q0.2;
assert (Q0.1*Q0.2)*(Q0.1*Q0.2) eq (1/2*(al-1)*(al+1/2-1) - al/2*(al+1/2))*(Q0.1+Q0.2)
                                    + ((1-al)*(al-1/2+1) + al^2 + 3/2*al + 2*(1/2)^2 -1/2)*Q0.1*Q0.2;

// Also type (d) when bt = 1/2 - these are isomorphic!!
// In fact, the axes here are Z-graded

Ial := ideal<A | A.3>;
assert Dimension(Ial) eq 1;

// This is \widehat{S(2)^circ}
Qal, pi := quo<A | Ial>;
assert HasJordanFusionLaw(Qal.1:fusion_value:=1/2);
assert HasJordanFusionLaw(Qal.2:fusion_value:=1/2);
assert Dimension(Annihilator(Qal)) eq 1;
assert Qal.1*Qal.2 eq 1/2*(Qal.1+Qal.2) + Qal.3;

// So I0+Ial is an ideal
// quotient is S(2)^\circ

// A.1-A.2 generates the entire R
assert A.2*(A.1-A.2+A.3-2*A.4) eq 1/2*(A.1-A.2+A.3-2*A.4) +(2*al-1)*A.3 +2*A.4;
// so (2*al-1)*A.3 +2*A.4 is in the ideal.
// but ideals must be the sum of eigenspaces, so this is all of R
assert ideal<A | A.1-A.2> eq R;

/////////////////////////////
// Second case, if mu ne 1 and al = -1

F<mu> := FunctionField(QQ);
A, gens, frob := IY3(-1, mu);

null := NullSpace(frob);
P<t> := PolynomialRing(F);
assert  CharacteristicPolynomial(frob) eq t*(t-1)*(t-3*(mu+1))*(t+3*(mu-1));
// So if mu ne -1, 1, then the dimension of the nullspace is 1

assert Dimension(null) eq 1;
R := ideal<A | [A!v : v in Basis(null)]>;
assert Annihilator(A) eq R;
assert A.4 in R;

Q, pi := quo<A|R>;
// So the eigenvalues are 1, -1, 1/2
// This is IY3(-1,1/2,mu)^\times

// The case of mu = 1 is dealt with above
// so do mu = -1

A, gens, frob := IY3(Rationals()!-1, -1);
a0 := gens[1];

null := NullSpace(frob);
assert Dimension(null) eq 2;
R := ideal<A | [A!v : v in Basis(null)]>;
assert A.1+A.2 in R and A.4 in R;
// These are the bt- and 0-eigenvectors for A.1
assert a0*(A.1+A.2) eq 1/2*(A.1+A.2);

// So these are the only candidates for a 1-dim ideal.

assert Annihilator(A) eq sub<A|A.4>;
// The quotient here is IY3(-1,1/2,1)^\times

assert gens[2]*(A.1+A.2) eq 1/2*(A.1+A.2);
// so this is a common bt-eigenspace.
Ibt := ideal<A|A.1+A.2>;
assert Dimension(Ibt) eq 1;

// It's quotient must be of Jordan type -1 and so isomorphic to 3C(-1)
Qbt, pi := quo<A|Ibt>;
a := gens[1]@pi;
b := gens[2]@pi;

c := a+b +2*a*b;
assert IsIdempotent(c);

// So the quotient by R is 3C(-1)^\times

/////////////////////////////
// Third case, if mu ne 1 and al ne -1

A, gens, frob := IY3();

P<t> := PolynomialRing(F);
assert CharacteristicPolynomial(frob) eq (t -(al+1))*(t + (al-2))*(t+(1-mu)*(al+1)*(al-2))*(t+(1+mu)*(al+1)*(al-2));
// so as expected the critical values are when mu = \pm 1 and al = -1, al = 2

// By above, can assume that mu ne 1 and al ne -1

// al = 2
A, gens, frob := IY3();
FF<al,mu> := BaseRing(A);

F<mu> := FunctionField(QQ);
phi := hom<FF->F | [2,mu]>;

A := ChangeRing(A, F, phi);
frob := ChangeRing(frob, F, phi);

null := NullSpace(frob);
assert Dimension(null) eq 3;
R := ideal<A | [ Eltseq(v) : v in Basis(null)]>;
assert A.1 in R and A.2 in R and A.4 in R;

// The Miyamoto group has a 2-dim module generated by A.1 and A.2 and fixes A.4

assert A.1*A.4 eq -A.1;
assert A.2*A.4 eq -A.2;
// hence A.4 does not span a 1-dimensional ideal
// In particular, this is R in any characteristic

assert A.1*A.1 eq -3*A.4;
assert A.2*A.2 eq -3*A.4;
assert A.1*A.2 eq -3*mu*A.4;

// If re+sf generates a proper ideal then need r + mu s = 0 = r mu + s
// Then mu^2 = 1 and so mu = 1 and r=s=1

// In this case, e+f is an ideal and so 

// so as char F ne 3, the only ideal is R

// mu = -1
A, gens, frob := IY3();
FF<al,mu> := BaseRing(A);

F<al> := FunctionField(QQ);
phi := hom<FF->F | [al,-1]>;

A := ChangeRing(A, F, phi);
frob := ChangeRing(frob, F, phi);

null := NullSpace(frob);
assert Dimension(null) eq 1;
R := ideal<A | [ Eltseq(v) : v in Basis(null)]>;
assert A.1+A.2 in R;
// This can only be the common bt-eigenspace
// So the quotient is 3C(al)


// -------------------------------------------
//
// Check isomorphisms

// mu = -1 gives 3 axes
M := Matrix(Rationals(),2,2,[1,-1/2,-1/2,1]);
A, frob := SplitSpinFactor(M);
F<al> := BaseRing(A);

a1 := 1/2*(A.1+al*A.3+(al+1)*A.4);
a2 := 1/2*(A.2+al*A.3+(al+1)*A.4);

t1 := MiyamotoInvolution(a1,1/2);
t2 := MiyamotoInvolution(a2,1/2);
assert Order(t1*t2) eq 3;

a3 := a1*t2;

so, id := HasOne(A);
assert so;
assert id eq A.3+A.4;

lm := -al*(3*al^2+3/2*al-3/2)/(4*(2*al-1));
assert lm eq -3/8*al*(al+1);
z := lm*id;

bas := [a1,a2,a3,z];
assert forall{v : v in bas | z*v eq lm*v};

assert a1*a2 eq (al+1/2)/2*(a1+a2) + (al-1/2)/2*a3 + z;

// So IY_3(al,1/2,-1/2) \cong 3A(al, 1/2)


// Look at char 3
M := Matrix(GF(3),2,2,[1,1,1,1]);
A, frob := SplitSpinFactor(M);
F<al> := BaseRing(A);

a1 := 1/2*(A.1+al*A.3+(al+1)*A.4);
a2 := 1/2*(A.2+al*A.3+(al+1)*A.4);

t1 := MiyamotoInvolution(a1,1/2);
t2 := MiyamotoInvolution(a2,1/2);
assert Order(t1*t2) eq 3;

a3 := a1*t2;
so, id := HasOne(A);
assert so;
assert id eq A.3+A.4;

// So this is not isomorphic to 3A(al,1/2) in char 3 as 3A has no id and instead has an annihilator.
// The quotient 3A/Ann \cong 3C(-1) in char 3.

assert Dimension(Nullspace(frob)) eq 1;
R := ideal<A|[ A!v : v in Basis(Nullspace(frob))]>;
assert A.1-A.2 in R;

B,quo := quo<A|R>;
// We are quotienting by difference of axes, so all axes are equal in the quotient.
assert a1-a2 in R and a1-a3 in R;


// There are additional axes in the quotient
z1 := A.3;
assert HasJordanFusionLaw(z1@quo: fusion_value:=al);
d := 1/2*(-A.1 + al*A.3+(al+1)*A.4);

assert HasJordanFusionLaw(d@quo: fusion_value:=al);
assert a1*z1- al/2*(a1+z1-d) in R;
// so quotient is 3C(al), but the image of our generating axes only gives us 1 axis, not 2.




// ----------------------------------------------
//
// Check idempotents
//

// Split spin factor paper covers all cases except IY3(al,1)
F<al> := FunctionField(QQ);
A, gens, frob := IY3(al,1);

I := IdempotentIdeal(A);
prim := PrimaryDecomposition(I);

assert #prim eq 2;
assert exists(J0){ J : J in prim | Dimension(J) eq 0};
assert VarietySizeOverAlgebraicClosure(J0) eq 1;
// This is the just the 0 vector

assert exists(J1){ J : J in prim | Dimension(J) eq 1};
P<t1,t2,t3,t4> := Generic(J1);

assert J1 eq ideal<P | t1+t2-1, t2^2-t2+t4/2, t3 + t4/2>;
// NB in the forbidden paper, there is an extra (2al-1) which is wrong!
// These are all axes

// =========================================================
//
// IY5
//
// =========================================================
A, gens, frob := IY5();
F<al> := BaseRing(A);

assert not HasOne(A);

assert HasMonsterFusionLaw(A.3: fusion_values:=[al, 1/2]);
u4 := A.1-4*A.2+6*A.3-4*A.4+A.5;
v0_2 := 2*A.3 - (A.2+A.4) +2/(al-1/2)*A.6;

val := 2*A.3 - (A.2+A.4) - 4*A.6;

vbt_1 := A.1-A.5;
vbt_2 := A.2-A.4;

assert A.3*u4 eq 0;
assert A.3*v0_2 eq 0;

assert A.3*val eq al*val;

assert A.3*vbt_1 eq 1/2*vbt_1;
assert A.3*vbt_2 eq 1/2*vbt_2;


// Subalgebras??
// No axial subalgebras - show that a_0 and a_i generate A

// No ideals containing an axis
assert forall{i : i in [2..5] | frob[1,i] eq 1};

R := ideal<A | [A!Vector(v) : v in Basis(NullSpace(frob))]>;

z := A.6;
assert z in R;
assert forall{i : i in [1..4] | A.i - A.(i+1) in R};

// Get the group
t1 := MiyamotoInvolution(A.1);
t2 := MiyamotoInvolution(A.2);

f := Matrix(F,[[1,-5,10,-10,5, 0],
              [0, 0, 0, 0, 1, 0],
              [0, 0, 0, 1, 0, 0],
              [0, 0, 1, 0, 0, 0],
              [0, 1, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 1]]);

assert forall{<i,j> : j in [i..6], i in [1..6] | (A.i*f)*(A.j*f) eq (A.i*A.j)*f};

Miy := sub<GL(6,F)|t1,t2>;

G := sub<GL(6,F) | t1,t2,f>;

// First examine the G-module structure of R
// In this case the Miy group is D_\infty, or if the field has char p, then it is D_2p (D_2*9 if char F eq 3)
// Note that either the Miy is infinite, or we are in modular rep theory.

// Clear z is fixed by Miy
// This has a complement N4

M := GModule(Miy);
N1 := sub<M | M.1-M.2>;
assert Dimension(N1) eq 4;

// So the G-module structure of the radical is 1+4, where <z> \oplus N4

// N1 is a uniserial module

// take differences: M.1-M.2 - (M.2-M.3) = M.1-2*M.2+M.3
N2 := sub<M | M![1,-2,1,0,0,0]>;
assert Dimension(N2) eq 3;
// take differences: M.1-2*M.2+M.3 - (M.1-2*M.2+M.3) = M.1-3*M.2+3*M.3-M.4
N3 := sub<M | M![1,-3,3,-1,0,0]>;
assert Dimension(N3) eq 2;
// take differences: M.1-3*M.2+3*M.3-M.4 - (M.2-3*M.3+3*M.4-M.5) = M.1-4*M.2+6*M.3-4*M.4+M.5
N4 := sub<M | M![1,-4,6,-4,1,0]>;
assert Dimension(N4) eq 1;
// this is the element u1

// NB Still hold in char 3

// indecomposible modules are generated by z, or lm z + u_k, for some lm.
// So modules are generated by lm z + u_k, or are <z>, <z, u_k>, or <u_k>

// Let u_k = \sum{i=0}^k (-1)^i \binom{k}{i} a_i
u1 := A![1,-1,0,0,0,0];
u2 := A![1,-2,1,0,0,0];
u3 := A![1,-3,3,-1,0,0];
u4 := A![1,-4,6,-4,1,0];
z := A.6;

// These span R and so are a basis for R
assert forall{ x : x in [z,u1,u2,u3,u4] | x in R};

// Now we record the multiplications we will need.
// First for u1
Ann := Annihilator(A);
assert Dimension(Ann) eq 1;
assert u4 in Ann;

assert z^2 eq (2*al-3)*(2*al-1)/32*u4;
assert A.2*z eq (2*al-1)/8*( u2 + 4*z );

assert A.3*u3 eq -1/4*u4 + 1/2*u3;
assert A.4*u3 eq -3/4*u4 + 1/2*u3;
assert A.5*u3 eq -5/4*u4 + 1/2*u3;
assert A.6*u3 eq 0;

assert A.2*u2 eq           1/2*u2 + 2*z;
assert A.3*u2 eq -1/4*u4 + 1/2*u2 + 2*z;
assert A.4*u2 eq     -u4 + 1/2*u2 + 2*z;
assert A.5*u2 eq -9/4*u4 + 1/2*u2 + 2*z;
assert A.6*u2 eq 1/8*(2*al-1)*u4;

assert A.2*u1 eq           1/2*u1 + z;
assert A.3*u1 eq -1/4*u4 + 1/2*u1 + 3*z;
assert A.4*u1 eq -5/4*u4 + 1/2*u1+ 5*z;
assert A.5*u1 eq -7/2*u4 + 1/2*u1 + 7*z;
assert A.6*u1 eq 1/8*(2*al-1)*(u3+u4);

// In the basis A.2, u1,u2,u3,u4,z
assert A.2*z eq (2*al-1)/8*( u2 + 4*z );
assert z^2 eq (2*al-3)*(2*al-1)/32*u4;

assert A.2*u3 eq 1/4*(2*u3 + u4);
assert u1*u3 eq 1/2*u4;
assert u2*u3 eq 0;
assert u3*u3 eq 0;
assert z*u3 eq 0;

assert A.2*u2 eq 1/2*(u2 + 4*z);
assert u1*u2 eq -1/4*u4;
assert u2*u2 eq -1/2*u4;
assert z*u2 eq (2*al-1)/8*u4;

assert A.2*u1 eq 1/2*(u1 + 2*z);
assert u1*u1 eq -2*z;
assert z*u1 eq (2*al-1)/8*(u3+u4);


// Already know that Ann eq <u4>
// Check the ideals generated by <ui>

// By above, <u3> is a 2-dim ideal, spanned by u3 and u4.
I3 := ideal<A|u3>;
assert Dimension(I3) eq 2;
assert u4 in I3 and u3 in I3;

// By above, z in <u2>
I2 := ideal<A|u2>;
assert Dimension(I2) eq 4;
assert u4 in I2 and u3 in I2 and u2 in I2 and z in I2;

// By above, z in <u1>
assert ideal<A|u1> eq R;

// From the above, <z> does not generate a 1-dim ideal.
// u4, u3, u2, z in <z> = <z,u2> = <u2>
assert ideal<A|z> eq I2;

// Already seen z in <u1> = R.
// Also from above, <u4, z> = <u4, u2, z> = <u2>
// And similarly <u3, z> = <u3, u2, z> = <u2>

// Now consider ideals generated by lm z + u_k

// For lm z + u1, multiplying by (3A.3-A.2)  implies that u1 + lm(2al-1)z in I
// Hence so we need al = 1, a contradiction.
// So u1 and z in ideal
// So this generates R
// eg
assert ideal<A|u1+z> eq R;

// For lm z + u2, there are two options:
// either lm = 4, so that a_i(u2+4z) gives mu(u2+4z) + some amount of u3 and u4
// or lm = -4/(2al-1), so that a_i(u2+lmz) eq 0 + some amount of u3 and u4
// otherwise I = <u2,z> = <u2> = I2 which is 4-dim
x := u2 + 4*z;
Ix := ideal<A | x>;
assert Dimension(Ix) eq 3;
assert x in Ix and u3 in Ix and u4 in Ix;

y := u2 - 2/(al-1/2)*z;
assert A.2*y eq 0;
Iy := ideal<A | y>;
assert Dimension(Iy) eq 3;
assert y in Iy and u3 in Iy and u4 in Iy;

// for lm z + u3
assert (A.2-A.3)*u3 eq 1/2*u4;
assert (A.2-A.3)*z eq (2*al-1)/8*u3;
// so u_3 in the ideal and hence z is.  So now by above u_2 is
// So we get <u2, z> = <u2> = I2, which is 4 dim
// eg
assert ideal<A|z+u3> eq I2;

// Similarly for lm z + u4
// We get <u4, z>
assert ideal<A|z+u4> eq I2;

// ---------------------------------------------------
// Now investigate the quotients

B4, quo4 := quo<A | Ann>;
assert not HasOne(B4);
assert Dimension(Annihilator(B4)) eq 0;

assert A.1@quo4 eq B4.1 and A.2@quo4 eq B4.2;
assert sub<B4 | B4.1, B4.2> eq B4;
assert HasMonsterFusionLaw(B4.1:fusion_values:=[al,1/2]);
assert Dimension(Eigenspace(B4.1, 0)) eq 1;
assert Dimension(Eigenspace(B4.1, al)) eq 1;
assert Dimension(Eigenspace(B4.1, 1/2)) eq 2;
// This is IY5^x

assert Vector(u3@quo4) in Eigenspace(B4.1, 1/2);

// ---------------------------------------------------
B3, quo3 := quo<A|I3>;
assert not HasOne(B3);
assert Dimension(Annihilator(B3)) eq 1;

// This is a new algebra!!
assert A.1@quo3 eq B3.1 and A.2@quo3 eq B3.2;
assert sub<B3 | B3.1, B3.2> eq B3;
// The fusion law is Monster type, but with gaps.
// 0*0, 0*al, al*al are all empty
assert HasMonsterFusionLaw(B3.1:fusion_values:=[al,1/2]);
assert Dimension(Eigenspace(B3.1, 0)) eq 1;
assert Dimension(Eigenspace(B3.1, al)) eq 1;
assert Dimension(Eigenspace(B3.1, 1/2)) eq 1;
// It is 4-dim and has al in eigenspace

assert y@quo3 in Annihilator(B3);
assert Vector(x@quo3) in Eigenspace(B3.1, al);
// Looking at the fusion law, either of these gives a 1-dim ideal, which matches above analysis.

// ---------------------------------------------------
Bx, quox := quo<A|Ix>;
assert not HasOne(Bx);
assert Dimension(Annihilator(Bx)) eq 1;

assert A.1@quox eq Bx.1 and A.2@quox eq Bx.2;
assert sub<Bx | Bx.1, Bx.2> eq Bx;
assert HasJordanFusionLaw(Bx.1:fusion_value:=1/2);

zz := -(2*al-1)/8/al*y@quox;
assert zz in Annihilator(Bx);

assert Bx.1*Bx.2 eq 1/2*(Bx.1 + Bx.2) + zz;
// So this is \widehat{S}(2)^\circ

// ---------------------------------------------------
By, quoy := quo<A | Iy>;
assert not HasOne(By);
assert Dimension(Annihilator(By)) eq 0;

assert A.1@quoy eq By.1 and A.2@quoy eq By.2;
assert sub<By | By.1, By.2> eq By;
assert HasMonsterFusionLaw(By.1:fusion_values:=[al,1/2]);
assert Dimension(Eigenspace(By.1, 0)) eq 0;
assert Dimension(Eigenspace(By.1, al)) eq 1;
assert Dimension(Eigenspace(By.1, 1/2)) eq 1;
// Fusion law has gaps with al*al and al*1/2 empty

u := (x/2/al)@quoy;
// u is the common al eigenspace
assert forall{ i : i in [1..3] | By.i*u eq al*u};
// This is a 1-dim ideal, which fits the above picture

w := By.1*By.2;
assert w*w eq (1/4-al)*(By.1+By.2) + (2*al+1/2)*w;
// This is Maddy Whybrow's example in fusion law (a), when bt = 1/2 and x=1 in
// Graded 2-generated axial algebras, https://arxiv.org/abs/2005.03577
// Also type (d)


// -----------------------------------------------------
B2, quo2 := quo<A | I2>;
assert Dimension(B2) eq 2;
assert A.1@quo2 eq B2.1 and A.2@quo2 eq B2.2;
assert B2.1*B2.2 eq 1/2*(B2.1+B2.2);
// so the quotient is S(2)^\circ

// ---------------------------------
//
// We need some additional identities for the idempotents section

zp := -(2*al-1)/8/al*y;

u2p := (u2+4*z);
assert u2p^2 eq 2*al*(al-1)*u4;
assert u2p*u3 eq 0;

assert A.1*A.2 eq 1/2*(A.1+A.2) + zp + (2*al-1)/8/al*u2p;

assert A.1*zp eq (2*al-1)/16/al*(u3 +3/2*u4);
assert A.2*zp eq 0;
assert zp^2 eq -(2*al-1)/32/al*u4;

assert A.1*u2p eq al*u2p + (2*al-1)/2*u3 + (4*al-3)/4*u4;
assert A.2*u2p eq al*u2p;
assert zp*u2p eq 0;

assert A.1*u3 eq 1/2*u3+3/4*u4;
assert A.2*u3 eq 1/2*u3+1/4*u4;
assert zp*u3 eq 0;


K<lm, mu2, mu3, m4> := PolynomialRing(F, 4);

AK := ChangeRing(A, K);
Y := lm*AK.1 + (1-lm)*AK.2 + 2*lm*(1-lm)*AK!Eltseq(zp);

X := Y + mu2*AK!Eltseq(u2p) + mu3*AK!Eltseq(u3) + mu4*AK!Eltseq(u4);

// can use this to check the polys are correct
// Slight error in next line, but it works out as seen below
//assert X^2 eq Y+ (-(2*al - 1)*lm*(lm-1)/4/al + 2*al*mu2)*AK!Eltseq(u2p) + mu3*AK!Eltseq(u3)+ 1/2*(-(2*al - 1)/(4*al)*(lm^2 + lm + -2)*lm^2 + (4*al - 3)*lm*mu2 + 4*al*(al - 1)*mu2^2 + (2*lm + 1)*mu3)*AK!Eltseq(u4);


// --------------------------------------------------------
//
// idempotents
//
// --------------------------------------------------------
A, gens, frob := IY5();
F<al> := BaseRing(A);
I := IdempotentIdeal(A);
P := Generic(I);

prim := PrimaryDecomposition(I);

assert #prim eq 2;
assert exists(J0){ J : J in prim | Dimension(J) eq 0};

assert exists(J2){ J : J in prim | Dimension(J) eq 2};

// In the ideal of dim 0, there is only 0
assert VarietySizeOverAlgebraicClosure(J0) eq 1;
assert Variety(J0) eq [<0,0,0,0,0,0>];

// For J2, z = 0
assert P.6 in J2;
// sum of the axes is 1 in J2
assert &+[P.i : i in [1..5]] -1 in J2;

KK<s,t> := PolynomialRing(F,2);
AA := ChangeRing(A,KK);
Y := s*AA.1 + (1-s)*AA.2 + 2*s*(1-s)*AA!Eltseq(zp);
X:= s*(s-1)/4/al*AA!Eltseq(u2p) + t*AA!Eltseq(u3) + (s^2*(1-s^2)/4+(1+2*s)*t)/2*AA!Eltseq(u4) + Y;

assert IsIdempotent(X);

assert CharacteristicPolynomial(AdjointMatrix(X)) eq CharacteristicPolynomial(AdjointMatrix(AA.1));
assert IsIndependent([A.1,A.2,zp,u2p,u3,u4]);
// Group must be block triangular wrt 

AA := ChangeRing(AA, FieldOfFractions(KK));
X := AA!Eltseq(ChangeRing(X, FieldOfFractions(KK)));
assert InnerProduct(Vector(X)*ChangeRing(frob, FieldOfFractions(KK)), Vector(X)) eq 1;

X01 := (s+2)*AA.1 -2*(3*s+4)*AA.3 + 8*(s+1)*AA.4 -(3*s+2)*AA.5 -16/(2*al-1)*AA.6;
X02 := (s+2)*AA.2 -(3*s+5)*AA.3 + (3*s+4)*AA.4 -(s+1)*AA.5 -4/(2*al-1)*AA.6;
Xal := (s+1)*(s+2)*AA.1 -2*(s+2)*(2*s+1)*AA.2 + 2*(3*s^2+6*s+1)*AA.3 -2*s*(2*s+3)*AA.4
            +s*(s+1)*AA.5 + 8*AA.6;
Xbt1 := (2*s^3 + 8*s^2 + 15*s - 4*t + 10)*AA.1 -2*(6*s^3 + 16*s^2 + 15*s - 12*t + 5)*AA.3
          +16*(s^3 + 2*s^2 + s - 2*t)*AA.4 - (6*s^3 + 8*s^2 + s - 12*t)*AA.5;
Xbt2 := (2*s^3 + 8*s^2 + 15*s - 4*t + 10)*AA.2 -(6*s^3 + 20*s^2 + 29*s - 12*t + 15)*AA.3
          + (6*s^3 + 16*s^2 + 17*s - 12*t + 6)*AA.4 -(2*s^3 + 4*s^2 + 3*s - 4*t + 1)*AA.5;

assert X*X01 eq 0;
assert X*X02 eq 0;
assert X*Xal eq al*Xal;
assert X*Xbt1 eq 1/2*Xbt1;
assert X*Xbt2 eq 1/2*Xbt2;


assert X eq   1/8*(-s*(s^3-5*s-4) + 4*(2*s+3)*t)*AA.1
            + 1/2*(s^2*(s^2-3) -2*(4*s+5)*t + 2)*AA.2
            + 1/4*(-s*(3*s^3-5*s +2) +24*(s+1)*t)*AA.3
            + 1/2*(-s^2*(1-s^2) - 2*(4*s+3)*t)*AA.4
            + 1/8*(s^2*(1-s^2) + 4*(2*s+1)*t)*AA.5;

// We know the form of the axis a_n.
// When does X equal a_n?

P<n,s,t> := PolynomialRing(Rationals(), 3);

eq1 := 1/24*(n-1)*(n-2)*(n-3)*(n-4) - 1/8*(-s*(s^3-5*s-4) + 4*(2*s+3)*t);
eq2 := -1/6*n*(n-2)*(n-3)*(n-4) - 1/2*(s^2*(s^2-3) -2*(4*s+5)*t + 2);
eq3 := 1/4*n*(n-1)*(n-3)*(n-4) - 1/4*(-s*(3*s^3-5*s +2) +24*(s+1)*t);
eq4 := -1/6*n*(n-1)*(n-2)*(n-4) - 1/2*(-s^2*(1-s^2) - 2*(4*s+3)*t);
eq5 := 1/24*n*(n-1)*(n-2)*(n-3) - 1/8*(s^2*(1-s^2) + 4*(2*s+1)*t);

eq1 *:= 24;
eq2 *:= -6;
eq3 *:= 4;
eq4 *:= -6;
eq5 *:= 24;

assert n*eq1 - (n-1)*eq2 eq n*(-6*(s*(s+2) + t+1)) + 3*s^2*(s^2-3) -6*(4*s+5)*t +6;
assert (n-1)*eq2 - (n-2)*eq3 eq n*(2*(-s*(2*s+1) -3*(t-1))) + s*(3*s^3-s+4) -6*(4*s+3)*t -6;
assert (n-2)*eq3 - (n-3)*eq4 eq n*(-2*(s*(s-1)+3*t)) + s*(3*s^3 +s-4) -6*(4*s+1)*t;
assert (n-3)*eq4 - (n-4)*eq5 eq n*(-6*t) + 3*( s^2*(s^2-1) - 2*(4*s-1)*t);

// Now eliminate the n using the last equation each time

e1 := 3*( s^2*(s^2-1) - 2*(4*s-1)*t)*(-6*(s*(s+2) + t+1)) +6*t*(3*s^2*(s^2-3) -6*(4*s+5)*t +6);
e2 := 3*( s^2*(s^2-1) - 2*(4*s-1)*t)*(2*(-s*(2*s+1) -3*(t-1))) +6*t*(s*(3*s^3-s+4) -6*(4*s+3)*t -6);
e3 := 3*( s^2*(s^2-1) - 2*(4*s-1)*t)*(-2*(s*(s-1)+3*t)) +6*t*( s*(3*s^3 +s-4) -6*(4*s+1)*t);

e1 *:= 1/18;
e2 *:= 1/6;
e3 *:= 1/6;

assert e3-e1 eq s*( s*(3*s^3 + s^2 - 3*s - 1) - 6*(3*s+1)*t);
assert  e2-2*e3 eq s*( s*(-3*s^3 + 3*s^2 + 3*s - 3) + 18*(s-1)*t);

// So either s = 0
assert Evaluate(e1, 2,0) eq -12*t^2;
// so t = 0 and hence x = 0

// So can divide the two equations above through by s
d1 := (e3-e1)/s;
d2 := (e2-2*e3)/s;

assert d1 + d2 eq 4*( s*(s^2-1) -6*t);

// so t = 1/6*s*(s^2-1) is the solution

assert Evaluate(e1, 3, 1/6*s*(s^2-1)) eq 0;
assert Evaluate(e2, 3, 1/6*s*(s^2-1)) eq 0;
assert Evaluate(e3, 3, 1/6*s*(s^2-1)) eq 0;

// Find the value for n

eq1n := Evaluate(eq1, 3, 1/6*s*(s^2-1));
eq2n := Evaluate(eq2, 3, 1/6*s*(s^2-1));
eq3n := Evaluate(eq3, 3, 1/6*s*(s^2-1));
eq4n := Evaluate(eq4, 3, 1/6*s*(s^2-1));
eq5n := Evaluate(eq5, 3, 1/6*s*(s^2-1));

assert eq1n - eq5n eq 4*(-n^3 + 6*n^2 - 11*n - s^3 - 3*s^2 - 2*s + 6);
assert eq2n - eq5n eq 3*(-n^3 + 5*n^2 - 6*n - s^3 - 2*s^2 + s + 2);
assert eq3n - eq5n eq 2*(-n^3 + 4*n^2 - 3*n - s^3 - s^2 + 2*s);
assert eq4n - eq5n eq -n^3 + 3*n^2 - 2*n - s^3 + s;

d15 := (eq1n - eq5n)/4;
d25 := (eq2n - eq5n)/3;
d35 := (eq3n - eq5n)/2;
d45 := eq4n - eq5n;

assert d15-d45 eq 3*(n^2 - 3*n - s^2 - s + 2);
assert d25-d45 eq 2*(n^2 - 2*n - s^2 + 1);
assert d35-d45 eq n^2 - n - s^2 + s;

d15_45 := (d15-d45)/3;
d25_45 := (d25-d45)/2;
d35_45 := d35-d45;

assert d15_45 - d35_45 eq 2*(-n-s+1);
assert d25_45 - d35_45 eq -n-s+1;

// so n = s+1, t = 1/6*s*(s^2-1) is the solution

// --------------------------------
//
// Check for singular points
II := IdealOfSingularPoints(A);
P2 := Generic(II);

primII := RadicalDecomposition(II);
assert #primII eq 2;

// Can't have al = 1/2
good := [ J : J in primII | P2.7-1/2 notin J ];
assert #good eq 1;

Jsing := good[1];
// P.7 ie al does not feature in Jsing
assert forall{ f : f in Basis(Jsing) | Evaluate(f,7,0) eq f};

// So define a map back to P
phi := hom<P2->P | [P.i : i in [1..6]] cat [0]>;

assert Basis(Jsing)@phi eq Basis(J2);
// So the ideal is the same as for J2

