/*

Check the algebras which normally have the infinite axet

*/
AttachSpec("../2-gen Monster.spec");
AttachSpec("../../AxialTools/AxialTools.spec");

Attach("../Yabe_algebras.m");

load "Find idempotents.m";
QQ := Rationals();
// =========================================================
//
// IY3
//
// =========================================================

// The matrix [[1,mu],[mu,1]] has rank drop iff mu = pm 1.  This gives a non-trivial radical to the resulting algebra.
// This algebra should be simple provided al ne -1,2 and mu ne \pm 1

//////////////////////////////
// First case, if mu = 1
// This is the exceptional algebra
F<al> := FunctionField(QQ);
A, gens, frob := IY3(al,1);

_, _, FL := IdentifyFusionLaw(A.1: eigenvalues:=[1,0,al,1/2]);
Gr, gr := Grading(FL);
assert Order(Gr) eq Infinity();
assert NumberOfGenerators(Gr) eq 1;
assert IsAbelian(Gr);
// So the axes here are Z-graded
assert 2@gr eq 2*Gr.1;
assert 3@gr eq 2*Gr.1;
assert 4@gr eq Gr.1;
// But we can use a C_2-grading

null := NullSpace(frob);
assert Dimension(null) eq 3;
R := ideal<A | [A!v : v in Basis(null)]>;

assert A.1-A.2+A.3-2*A.4 in R and A.3 in R and A.4 in R;
assert A.1*(A.1-A.2+A.3-2*A.4) eq 1/2*(A.1-A.2+A.3-2*A.4);
// These vectors span the bt-, al-, 0-eigenspaces for A.1.  So these and their sums are the only candidates for ideals.

I0 := ideal<A | A.4>;
assert I0 eq Annihilator(A);
assert Dimension(I0) eq 1;

Q0, pi := quo<A | I0>;

assert A.1@pi eq Q0.1 and A.2@pi eq Q0.2;
assert Q0.1*Q0.2 eq 1/2*(Q0.1+Q0.2) + (al-1/2)*Q0.3;
assert Q0.1*Q0.3 eq al*Q0.3;
assert Q0.2*Q0.3 eq al*Q0.3;
assert Q0.3*Q0.3 eq Q0!0;
// This is Maddy Whybrow's example in fusion law (a), with bt = 1/2, x = 1 in
// Graded 2-generated axial algebras, https://arxiv.org/abs/2005.03577
assert Q0.1*(Q0.1*Q0.2) eq (al-1)*(1/2-1)*Q0.1 -al/2*Q0.2 +(al+1/2)*Q0.1*Q0.2;
assert (Q0.1*Q0.2)*(Q0.1*Q0.2) eq (1/2*(al-1)*(al+1/2-1) - al/2*(al+1/2))*(Q0.1+Q0.2)
                                    + ((1-al)*(al-1/2+1) + al^2 + 3/2*al + 2*(1/2)^2 -1/2)*Q0.1*Q0.2;

// Also type (d) when bt = 1/2 - these are isomorphic!!
// In fact, the axes here are Z-graded

Ial := ideal<A | A.3>;
assert Dimension(Ial) eq 1;

// This is \widehat{S(2)^circ}
Qal, pi := quo<A | Ial>;
assert HasJordanFusionLaw(Qal.1:fusion_value:=1/2);
assert HasJordanFusionLaw(Qal.2:fusion_value:=1/2);
assert Dimension(Annihilator(Qal)) eq 1;
assert Qal.1*Qal.2 eq 1/2*(Qal.1+Qal.2) + Qal.3;

// So I0+Ial is an ideal
// quotient is S(2)^\circ

// A.1-A.2 generates the entire R
assert A.2*(A.1-A.2+A.3-2*A.4) eq 1/2*(A.1-A.2+A.3-2*A.4) +(2*al-1)*A.3 +2*A.4;
// so (2*al-1)*A.3 +2*A.4 is in the ideal.
// but ideals must be the sum of eigenspaces, so this is all of R
assert ideal<A | A.1-A.2> eq R;

/////////////////////////////
// Second case, if mu ne 1 and al = -1

F<mu> := FunctionField(QQ);
A, gens, frob := IY3(-1, mu);

null := NullSpace(frob);
P<t> := PolynomialRing(F);
assert  CharacteristicPolynomial(frob) eq t*(t-1)*(t-3*(mu+1))*(t+3*(mu-1));
// So if mu ne -1, 1, then the dimension of the nullspace is 1

assert Dimension(null) eq 1;
R := ideal<A | [A!v : v in Basis(null)]>;
assert Annihilator(A) eq R;
assert A.4 in R;

Q, pi := quo<A|R>;
// So the eigenvalues are 1, -1, 1/2
// This is IY3(-1,1/2,mu)^\times

// The case of mu = 1 is dealt with above
// so do mu = -1

A, gens, frob := IY3(Rationals()!-1, -1);
a0 := gens[1];

null := NullSpace(frob);
assert Dimension(null) eq 2;
R := ideal<A | [A!v : v in Basis(null)]>;
assert A.1+A.2 in R and A.4 in R;
// These are the bt- and 0-eigenvectors for A.1
assert a0*(A.1+A.2) eq 1/2*(A.1+A.2);

// So these are the only candidates for a 1-dim ideal.

assert Annihilator(A) eq sub<A|A.4>;
// The quotient here is IY3(-1,1/2,1)^\times

assert gens[2]*(A.1+A.2) eq 1/2*(A.1+A.2);
// so this is a common bt-eigenspace.
Ibt := ideal<A|A.1+A.2>;
assert Dimension(Ibt) eq 1;

// It's quotient must be of Jordan type -1 and so isomorphic to 3C(-1)
Qbt, pi := quo<A|Ibt>;
a := gens[1]@pi;
b := gens[2]@pi;

c := a+b +2*a*b;
assert IsIdempotent(c);

// So the quotient by R is 3C(-1)^\times

/////////////////////////////
// Third case, if mu ne 1 and al ne -1

A, gens, frob := IY3();

P<t> := PolynomialRing(F);
assert CharacteristicPolynomial(frob) eq (t -(al+1))*(t + (al-2))*(t+(1-mu)*(al+1)*(al-2))*(t+(1+mu)*(al+1)*(al-2));
// so as expected the critical values are when mu = \pm 1 and al = -1, al = 2

// By above, can assume that mu ne 1 and al ne -1

// al = 2
A, gens, frob := IY3();
FF<al,mu> := BaseRing(A);

F<mu> := FunctionField(QQ);
phi := hom<FF->F | [2,mu]>;

A := ChangeRing(A, F, phi);
frob := ChangeRing(frob, F, phi);

null := NullSpace(frob);
assert Dimension(null) eq 3;
R := ideal<A | [ Eltseq(v) : v in Basis(null)]>;
assert A.1 in R and A.2 in R and A.4 in R;

// The Miyamoto group has a 2-dim module generated by A.1 and A.2 and fixes A.4

assert A.1*A.4 eq -A.1;
assert A.2*A.4 eq -A.2;
// hence A.4 does not span a 1-dimensional ideal
// In particular, this is R in any characteristic

assert A.1*A.1 eq -3*A.4;
assert A.2*A.2 eq -3*A.4;
assert A.1*A.2 eq -3*mu*A.4;

// If re+sf generates a proper ideal then need r + mu s = 0 = r mu + s
// Then mu^2 = 1 and so mu = 1 and r=s=1

// In this case, e+f is an ideal and so 

// so as char F ne 3, the only ideal is R

// mu = -1
A, gens, frob := IY3();
FF<al,mu> := BaseRing(A);

F<al> := FunctionField(QQ);
phi := hom<FF->F | [al,-1]>;

A := ChangeRing(A, F, phi);
frob := ChangeRing(frob, F, phi);

null := NullSpace(frob);
assert Dimension(null) eq 1;
R := ideal<A | [ Eltseq(v) : v in Basis(null)]>;
assert A.1+A.2 in R;
// This can only be the common bt-eigenspace
// So the quotient is 3C(al)


// -------------------------------------------
//
// Check isomorphisms

// mu = -1 gives 3 axes
M := Matrix(Rationals(),2,2,[1,-1/2,-1/2,1]);
A, frob := SplitSpinFactor(M);
F<al> := BaseRing(A);

a1 := 1/2*(A.1+al*A.3+(al+1)*A.4);
a2 := 1/2*(A.2+al*A.3+(al+1)*A.4);

t1 := MiyamotoInvolution(a1,1/2);
t2 := MiyamotoInvolution(a2,1/2);
assert Order(t1*t2) eq 3;

a3 := a1*t2;

so, id := HasOne(A);
assert so;
assert id eq A.3+A.4;

lm := -al*(3*al^2+3/2*al-3/2)/(4*(2*al-1));
assert lm eq -3/8*al*(al+1);
z := lm*id;

bas := [a1,a2,a3,z];
assert forall{v : v in bas | z*v eq lm*v};

assert a1*a2 eq (al+1/2)/2*(a1+a2) + (al-1/2)/2*a3 + z;

// So IY_3(al,1/2,-1/2) \cong 3A(al, 1/2)


// Look at char 3
M := Matrix(GF(3),2,2,[1,1,1,1]);
A, frob := SplitSpinFactor(M);
F<al> := BaseRing(A);

a1 := 1/2*(A.1+al*A.3+(al+1)*A.4);
a2 := 1/2*(A.2+al*A.3+(al+1)*A.4);

t1 := MiyamotoInvolution(a1,1/2);
t2 := MiyamotoInvolution(a2,1/2);
assert Order(t1*t2) eq 3;

a3 := a1*t2;
so, id := HasOne(A);
assert so;
assert id eq A.3+A.4;

// So this is not isomorphic to 3A(al,1/2) in char 3 as 3A has no id and instead has an annihilator.
// The quotient 3A/Ann \cong 3C(-1) in char 3.

assert Dimension(Nullspace(frob)) eq 1;
R := ideal<A|[ A!v : v in Basis(Nullspace(frob))]>;
assert A.1-A.2 in R;

B,quo := quo<A|R>;
// We are quotienting by difference of axes, so all axes are equal in the quotient.
assert a1-a2 in R and a1-a3 in R;


// There are additional axes in the quotient
z1 := A.3;
assert HasJordanFusionLaw(z1@quo: fusion_value:=al);
d := 1/2*(-A.1 + al*A.3+(al+1)*A.4);

assert HasJordanFusionLaw(d@quo: fusion_value:=al);
assert a1*z1- al/2*(a1+z1-d) in R;
// so quotient is 3C(al), but the image of our generating axes only gives us 1 axis, not 2.




// ----------------------------------------------
//
// Check idempotents
//

// Split spin factor paper covers all cases except IY3(al,1)
F<al> := FunctionField(QQ);
A, gens, frob := IY3(al,1);

I := IdempotentIdeal(A);
prim := PrimaryDecomposition(I);

assert #prim eq 2;
assert exists(J0){ J : J in prim | Dimension(J) eq 0};
assert VarietySizeOverAlgebraicClosure(J0) eq 1;
// This is the just the 0 vector

assert exists(J1){ J : J in prim | Dimension(J) eq 1};
P<t1,t2,t3,t4> := Generic(J1);

assert J1 eq ideal<P | t1+t2-1, t2^2-t2+t4/2, t3 + t4/2>;
// NB in the forbidden paper, there is an extra (2al-1) which is wrong!
// These are all axes

// ----------------------------------------------
//
// Check automorphism group when mu = 1

F<al>:=FunctionField(Rationals());
A, gens, frob := IY3(al,1);

bas := [A.1+A.2, A.1-A.2, A.3,A.4];
A := ChangeBasis(A, bas);

P := PolynomialRing(F, 8);
AP := ChangeRing(A, P);
g := Matrix([[1, P.1, P.2, P.3],
             [0, P.4, P.5, P.6],
             [0,   0, P.7, 0  ],
             [0,   0,   0, P.8]]);

assert (AP.1*AP.3)*g eq (AP.1*g)*(AP.3*g);

assert AP.2^2*g eq -(2*al-1)*P.7*AP.3 - 2*P.8*AP.4;
assert (AP.2*g)*(AP.2*g) eq P.4^2*(-(2*al-1)*AP.3-2*AP.4);

assert (AP.1*AP.2)*g eq P.4*AP.2 + P.5*AP.3 + P.6*AP.4;
assert (AP.1*g)*(AP.2*g) eq P.4*AP.2 + (2*al*P.5 -(2*al-1)*P.1*P.4)*AP.3 -2*P.1*P.4*AP.4;

assert AP.1^2*g eq 2*AP.1 + 2*P.1*AP.2 + (2*P.2 + (2*al-1)*P.7)*AP.3 + 2*(P.3 + P.8)*AP.4;
assert (AP.1*g)*(AP.1*g) eq 2*AP.1 + 2*P.1*AP.2 + ( (2*al-1)*(1-P.1^2) + 4*al*P.2)*AP.3 + 2*(1-P.1^2)*AP.4;

// So we get
assert AP.2^2*g - (AP.2*g)*(AP.2*g) eq (2*al-1)*(P.4^2-P.7)*AP.3 +2*(P.4^2-P.8)*AP.4;
assert (AP.1*AP.2)*g - (AP.1*g)*(AP.2*g) eq (2*al-1)*(P.1*P.4 - P.5)*AP.3 + (P.6 + 2*P.1*P.4)*AP.4;
assert AP.1^2*g - (AP.1*g)*(AP.1*g) eq (2*al-1)*( (P.1^2 - 1) - 2*P.2 + P.7)*AP.3 + 2*(P.3 + P.8 + P.1^2 - 1)*AP.4;

I := ideal<P |P.4^2-P.7, P.4^2-P.8, P.1*P.4 - P.5, P.6 + 2*P.1*P.4, (P.1^2 - 1) - 2*P.2 + P.7, P.3 + P.8 + P.1^2 - 1>;

// define everything in terms of P.1 and P.4
assert P.2 -1/2*(P.1^2+P.4^2-1) in I;
assert P.3 + (P.1^2+P.4^2-1) in I;
assert P.5 -P.1*P.4 in I;
assert P.6 +2*P.1*P.4 in I;
assert P.7-P.4^2 in I;
assert P.8 - P.4^2 in I;

P<gm1, dl1, gm2, dl2> := PolynomialRing(F,4);

AP := ChangeRing(A, P);

function aut(gm, dl)
  return Matrix([[1, gm, 1/2*(gm^2+dl^2-1), -(gm^2+dl^2-1)],
             [0, dl, gm*dl, -2*gm*dl],
             [0,   0, dl^2, 0  ],
             [0,   0,   0, dl^2]]);
end function;

g := aut(gm1, dl1);
h := aut(gm2, dl2);

assert g*h eq aut(gm1*dl2+gm2, dl1*dl2);

assert forall{<i,j> : i,j in [1..4] | (AP.i*g)*(AP.j*g) eq (AP.i*AP.j)*g};
// so g is an automorphism





// =========================================================
//
// IY5
//
// =========================================================
A, gens, frob := IY5();
F<al> := BaseRing(A);

assert not HasOne(A);

assert HasMonsterFusionLaw(A.3: fusion_values:=[al, 1/2]);
u4 := A.1-4*A.2+6*A.3-4*A.4+A.5;
v0_2 := 2*A.3 - (A.2+A.4) +2/(al-1/2)*A.6;

val := 2*A.3 - (A.2+A.4) - 4*A.6;

vbt_1 := A.1-A.5;
vbt_2 := A.2-A.4;

assert A.3*u4 eq 0;
assert A.3*v0_2 eq 0;

assert A.3*val eq al*val;

assert A.3*vbt_1 eq 1/2*vbt_1;
assert A.3*vbt_2 eq 1/2*vbt_2;


// Subalgebras??
// No axial subalgebras - show that a_0 and a_i generate A

// No ideals containing an axis
assert forall{i : i in [2..5] | frob[1,i] eq 1};

R := ideal<A | [A!Vector(v) : v in Basis(NullSpace(frob))]>;

z := A.6;
assert z in R;
assert forall{i : i in [1..4] | A.i - A.(i+1) in R};

// Get the group
t1 := MiyamotoInvolution(A.1);
t2 := MiyamotoInvolution(A.2);

f := Matrix(F,[[1,-5,10,-10,5, 0],
              [0, 0, 0, 0, 1, 0],
              [0, 0, 0, 1, 0, 0],
              [0, 0, 1, 0, 0, 0],
              [0, 1, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 1]]);

assert forall{<i,j> : j in [i..6], i in [1..6] | (A.i*f)*(A.j*f) eq (A.i*A.j)*f};

Miy := sub<GL(6,F)|t1,t2>;

G := sub<GL(6,F) | t1,t2,f>;

// First examine the G-module structure of R
// In this case the Miy group is D_\infty, or if the field has char p, then it is D_2p (D_2*9 if char F eq 3)
// Note that either the Miy is infinite, or we are in modular rep theory.

// Clear z is fixed by Miy
// This has a complement N4

M := GModule(Miy);
N1 := sub<M | M.1-M.2>;
assert Dimension(N1) eq 4;

// So the G-module structure of the radical is 1+4, where <z> \oplus N4

// N1 is a uniserial module

// take differences: M.1-M.2 - (M.2-M.3) = M.1-2*M.2+M.3
N2 := sub<M | M![1,-2,1,0,0,0]>;
assert Dimension(N2) eq 3;
// take differences: M.1-2*M.2+M.3 - (M.1-2*M.2+M.3) = M.1-3*M.2+3*M.3-M.4
N3 := sub<M | M![1,-3,3,-1,0,0]>;
assert Dimension(N3) eq 2;
// take differences: M.1-3*M.2+3*M.3-M.4 - (M.2-3*M.3+3*M.4-M.5) = M.1-4*M.2+6*M.3-4*M.4+M.5
N4 := sub<M | M![1,-4,6,-4,1,0]>;
assert Dimension(N4) eq 1;
// this is the element u1

// NB Still hold in char 3

// indecomposible modules are generated by z, or lm z + u_k, for some lm.
// So modules are generated by lm z + u_k, or are <z>, <z, u_k>, or <u_k>

// Let u_k = \sum{i=0}^k (-1)^i \binom{k}{i} a_i
u1 := A![1,-1,0,0,0,0];
u2 := A![1,-2,1,0,0,0];
u3 := A![1,-3,3,-1,0,0];
u4 := A![1,-4,6,-4,1,0];
z := A.6;

// These span R and so are a basis for R
assert forall{ x : x in [z,u1,u2,u3,u4] | x in R};

// Now we record the multiplications we will need.
// First for u1
Ann := Annihilator(A);
assert Dimension(Ann) eq 1;
assert u4 in Ann;

assert z^2 eq (2*al-3)*(2*al-1)/32*u4;
assert A.2*z eq (2*al-1)/8*( u2 + 4*z );

assert A.3*u3 eq -1/4*u4 + 1/2*u3;
assert A.4*u3 eq -3/4*u4 + 1/2*u3;
assert A.5*u3 eq -5/4*u4 + 1/2*u3;
assert A.6*u3 eq 0;

assert A.2*u2 eq           1/2*u2 + 2*z;
assert A.3*u2 eq -1/4*u4 + 1/2*u2 + 2*z;
assert A.4*u2 eq     -u4 + 1/2*u2 + 2*z;
assert A.5*u2 eq -9/4*u4 + 1/2*u2 + 2*z;
assert A.6*u2 eq 1/8*(2*al-1)*u4;

assert A.2*u1 eq           1/2*u1 + z;
assert A.3*u1 eq -1/4*u4 + 1/2*u1 + 3*z;
assert A.4*u1 eq -5/4*u4 + 1/2*u1+ 5*z;
assert A.5*u1 eq -7/2*u4 + 1/2*u1 + 7*z;
assert A.6*u1 eq 1/8*(2*al-1)*(u3+u4);

// In the basis A.2, u1,u2,u3,u4,z
assert A.2*z eq (2*al-1)/8*( u2 + 4*z );
assert z^2 eq (2*al-3)*(2*al-1)/32*u4;

assert A.2*u3 eq 1/4*(2*u3 + u4);
assert u1*u3 eq 1/2*u4;
assert u2*u3 eq 0;
assert u3*u3 eq 0;
assert z*u3 eq 0;

assert A.2*u2 eq 1/2*(u2 + 4*z);
assert u1*u2 eq -1/4*u4;
assert u2*u2 eq -1/2*u4;
assert z*u2 eq (2*al-1)/8*u4;

assert A.2*u1 eq 1/2*(u1 + 2*z);
assert u1*u1 eq -2*z;
assert z*u1 eq (2*al-1)/8*(u3+u4);


// Already know that Ann eq <u4>
// Check the ideals generated by <ui>

// By above, <u3> is a 2-dim ideal, spanned by u3 and u4.
I3 := ideal<A|u3>;
assert Dimension(I3) eq 2;
assert u4 in I3 and u3 in I3;

// By above, z in <u2>
I2 := ideal<A|u2>;
assert Dimension(I2) eq 4;
assert u4 in I2 and u3 in I2 and u2 in I2 and z in I2;

// By above, z in <u1>
assert ideal<A|u1> eq R;

// From the above, <z> does not generate a 1-dim ideal.
// u4, u3, u2, z in <z> = <z,u2> = <u2>
assert ideal<A|z> eq I2;

// Already seen z in <u1> = R.
// Also from above, <u4, z> = <u4, u2, z> = <u2>
// And similarly <u3, z> = <u3, u2, z> = <u2>

// Now consider ideals generated by lm z + u_k

// For lm z + u1, multiplying by (3A.3-A.2)  implies that u1 + lm(2al-1)z in I
// Hence so we need al = 1, a contradiction.
// So u1 and z in ideal
// So this generates R
// eg
assert ideal<A|u1+z> eq R;

// For lm z + u2, there are two options:
// either lm = 4, so that a_i(u2+4z) gives mu(u2+4z) + some amount of u3 and u4
// or lm = -4/(2al-1), so that a_i(u2+lmz) eq 0 + some amount of u3 and u4
// otherwise I = <u2,z> = <u2> = I2 which is 4-dim
zp := 1/4/al*(u2+4*z);
Izp := ideal<A | zp>;
assert Dimension(Izp) eq 3;
assert zp in Izp and u3 in Izp and u4 in Izp; 


np := -1/8/al*((2*al-1)*u2 - 4*z);
assert A.2*np eq 0;
Inp := ideal<A | np>;
assert Dimension(Inp) eq 3;
assert np in Inp and u3 in Inp and u4 in Inp;

// for lm z + u3
assert (A.2-A.3)*u3 eq 1/2*u4;
assert (A.2-A.3)*z eq (2*al-1)/8*u3;
// so u_3 in the ideal and hence z is.  So now by above u_2 is
// So we get <u2, z> = <u2> = I2, which is 4 dim
// eg
assert ideal<A|z+u3> eq I2;

// Similarly for lm z + u4
// We get <u4, z>
assert ideal<A|z+u4> eq I2;

// ---------------------------------------------------
// Now investigate the quotients

B4, quo4 := quo<A | Ann>;
assert not HasOne(B4);
assert Dimension(Annihilator(B4)) eq 0;

assert A.1@quo4 eq B4.1 and A.2@quo4 eq B4.2;
assert sub<B4 | B4.1, B4.2> eq B4;
assert HasMonsterFusionLaw(B4.1:fusion_values:=[al,1/2]);
assert Dimension(Eigenspace(B4.1, 0)) eq 1;
assert Dimension(Eigenspace(B4.1, al)) eq 1;
assert Dimension(Eigenspace(B4.1, 1/2)) eq 2;
// This is IY5^x

assert Vector(u3@quo4) in Eigenspace(B4.1, 1/2);

// ---------------------------------------------------
B3, quo3 := quo<A|I3>;
assert not HasOne(B3);
assert Dimension(Annihilator(B3)) eq 1;

assert np@quo3 in Annihilator(B3);

assert Vector(zp@quo3) in Eigenspace(B3.1, al);

assert A.1@quo3 eq B3.1 and A.2@quo3 eq B3.2;
assert sub<B3 | B3.1, B3.2> eq B3;

assert A.1*A.2 eq 1/2*(A.1+A.2) + (al-1/2)*zp + np;
assert zp^2 eq (al-1)/8/al*u4;

// So this is IY_3(al, 1/2, 1)

// The fusion law is Monster type, but with gaps.
// 0*0, 0*al, al*al are all empty
assert HasMonsterFusionLaw(B3.1:fusion_values:=[al,1/2]);
assert Dimension(Eigenspace(B3.1, 0)) eq 1;
assert Dimension(Eigenspace(B3.1, al)) eq 1;
assert Dimension(Eigenspace(B3.1, 1/2)) eq 1;
// It is 4-dim and has a common 0- and a common al- eigenspace

// Looking at the fusion law, either of these gives a 1-dim ideal, which matches above analysis.

// ---------------------------------------------------
Bzp, quozp := quo<A | Izp>;
assert not HasOne(Bzp);
assert Dimension(Annihilator(Bzp)) eq 1;

assert A.1@quozp eq Bzp.1 and A.2@quozp eq Bzp.2;
assert sub<Bzp | Bzp.1, Bzp.2> eq Bzp;
assert HasJordanFusionLaw(Bzp.1:fusion_value:=1/2);

assert np@quozp in Annihilator(Bzp);

assert Bzp.1*Bzp.2 eq 1/2*(Bzp.1 + Bzp.2) + np@quozp;
// So this is \widehat{S}(2)^\circ

// ---------------------------------------------------
Bnp, quonp := quo<A | Inp>;
assert not HasOne(Bnp);
assert Dimension(Annihilator(Bnp)) eq 0;

assert A.1@quonp eq Bnp.1 and A.2@quonp eq Bnp.2;
assert sub<Bnp | Bnp.1, Bnp.2> eq Bnp;
assert HasMonsterFusionLaw(Bnp.1:fusion_values:=[al,1/2]);
assert Dimension(Eigenspace(Bnp.1, 0)) eq 0;
assert Dimension(Eigenspace(Bnp.1, al)) eq 1;
assert Dimension(Eigenspace(Bnp.1, 1/2)) eq 1;
// Fusion law has gaps with al*al and al*1/2 empty

u := zp@quonp;
// u is the common al eigenspace
assert forall{ i : i in [1..3] | Bnp.i*u eq al*u};
// This is a 1-dim ideal, which fits the above picture

w := Bnp.1*Bnp.2;
assert w*w eq (1/4-al)*(Bnp.1+Bnp.2) + (2*al+1/2)*w;
// This is Maddy Whybrow's example in fusion law (a), when bt = 1/2 and x=1 in
// Graded 2-generated axial algebras, https://arxiv.org/abs/2005.03577
// Also type (d)


// -----------------------------------------------------
B2, quo2 := quo<A | I2>;
assert Dimension(B2) eq 2;
assert A.1@quo2 eq B2.1 and A.2@quo2 eq B2.2;
assert B2.1*B2.2 eq 1/2*(B2.1+B2.2);
// so the quotient is S(2)^\circ

// --------------------------------------------------------
//
// idempotents
//
// --------------------------------------------------------

// We compute some identities which support a theoretical proof.

assert A.1*A.2 eq 1/2*(A.1+A.2) + (al-1/2)*zp + np;

assert A.1*zp eq al*zp + (2*al-1)/8/al*u3 + (4*al-3)/16/al*u4;
assert A.2*zp eq al*zp;
assert zp*zp eq (al-1)/8/al*u4;

assert A.1*np eq (2*al-1)/16/al*(u3 +3/2*u4);
assert A.2*np eq 0;
assert np^2 eq -(2*al-1)/32/al*u4;

assert A.1*u3 eq 1/2*u3+3/4*u4;
assert A.2*u3 eq 1/2*u3+1/4*u4;
assert zp*u3 eq 0;
assert np*u3 eq 0;


K<lm, mu3, mu4> := PolynomialRing(F, 3);

AK := ChangeRing(A, K);
Y := lm*AK.1 + (1-lm)*AK.2 - lm*(1-lm)*AK!Eltseq(zp) + 2*lm*(1-lm)*AK!Eltseq(np);

X := Y + mu3*AK!Eltseq(u3) + mu4*AK!Eltseq(u4);

// can use this to check the polys are correct
// Slight error in next line, but it works out as seen below
//assert X^2 eq Y+ (-(2*al - 1)*lm*(lm-1)/4/al + 2*al*mu2)*AK!Eltseq(u2p) + mu3*AK!Eltseq(u3)+ 1/2*(-(2*al - 1)/(4*al)*(lm^2 + lm + -2)*lm^2 + (4*al - 3)*lm*mu2 + 4*al*(al - 1)*mu2^2 + (2*lm + 1)*mu3)*AK!Eltseq(u4);

assert X^2 eq Y + mu3*AK!Eltseq(u3)+ 1/2*( lm^2*(1-lm^2)/4 + (1+2*lm)*mu3 )*AK!Eltseq(u4);

// This allows us to solve for mu3 and mu4


// Check fusion law

KK<lm, mu3> := PolynomialRing(F, 2);

AA := ChangeRing(A, KK);
Y := lm*AA.1 + (1-lm)*AA.2 - lm*(1-lm)*AA!Eltseq(zp) + 2*lm*(1-lm)*AA!Eltseq(np);

mu4 :=  1/2*( lm^2*(1-lm^2)/4 + (1+2*lm)*mu3 );

X := Y + mu3*AA!Eltseq(u3) + mu4*AA!Eltseq(u4);

assert IsIdempotent(X);

assert CharacteristicPolynomial(AdjointMatrix(X)) eq CharacteristicPolynomial(AdjointMatrix(AA.1));
assert IsIndependent([A.1,A.2,zp,np,u3,u4]);
// Group must be block triangular wrt 

X01 := (lm+2)*AA.1 -2*(3*lm+4)*AA.3 + 8*(lm+1)*AA.4 -(3*lm+2)*AA.5 -16/(2*al-1)*AA.6;
X02 := (lm+2)*AA.2 -(3*lm+5)*AA.3 + (3*lm+4)*AA.4 -(lm+1)*AA.5 -4/(2*al-1)*AA.6;
Xal := (lm+1)*(lm+2)*AA.1 -2*(lm+2)*(2*lm+1)*AA.2 + 2*(3*lm^2+6*lm+1)*AA.3 -2*lm*(2*lm+3)*AA.4
            +lm*(lm+1)*AA.5 + 8*AA.6;
Xbt1 := (2*lm^3 + 8*lm^2 + 15*lm - 4*mu3 + 10)*AA.1 -2*(6*lm^3 + 16*lm^2 + 15*lm - 12*mu3 + 5)*AA.3
          +16*(lm^3 + 2*lm^2 + lm - 2*mu3)*AA.4 - (6*lm^3 + 8*lm^2 + lm - 12*mu3)*AA.5;
Xbt2 := (2*lm^3 + 8*lm^2 + 15*lm - 4*mu3 + 10)*AA.2 -(6*lm^3 + 20*lm^2 + 29*lm - 12*mu3 + 15)*AA.3
          + (6*lm^3 + 16*lm^2 + 17*lm - 12*mu3 + 6)*AA.4 -(2*lm^3 + 4*lm^2 + 3*lm - 4*mu3 + 1)*AA.5;

assert X*X01 eq 0;
assert X*X02 eq 0;
assert X*Xal eq al*Xal;
assert X*Xbt1 eq 1/2*Xbt1;
assert X*Xbt2 eq 1/2*Xbt2;


assert X eq   1/8*(-lm*(lm^3-5*lm-4) + 4*(2*lm+3)*mu3)*AA.1
            + 1/2*(lm^2*(lm^2-3) -2*(4*lm+5)*mu3 + 2)*AA.2
            + 1/4*(-lm*(3*lm^3-5*lm +2) +24*(lm+1)*mu3)*AA.3
            + 1/2*(-lm^2*(1-lm^2) - 2*(4*lm+3)*mu3)*AA.4
            + 1/8*(lm^2*(1-lm^2) + 4*(2*lm+1)*mu3)*AA.5;

// These all have Monster type
AAA := ChangeRing(AA, FunctionField(KK));
assert HasMonsterFusionLaw(AAA!Eltseq(X) : fusion_values:=[KK!al, 1/2]);

evals, espace, FL := IdentifyFusionLaw(AAA!Eltseq(X));
Gr, gr := Grading(FL);
assert Order(Gr) eq 2;

// Check the inner products

KK<lm1, mu1, lm2, mu2> := PolynomialRing(F, 4);

AA := ChangeRing(A, KK);
Y1 := lm1*AA.1 + (1-lm1)*AA.2 - lm1*(1-lm1)*AA!Eltseq(zp) + 2*lm1*(1-lm1)*AA!Eltseq(np);
X1 := Y1 + mu1*AA!Eltseq(u3) + 1/2*( lm1^2*(1-lm1^2)/4 + (1+2*lm1)*mu1)*AA!Eltseq(u4);

Y2 := lm2*AA.1 + (1-lm2)*AA.2 - lm2*(1-lm2)*AA!Eltseq(zp) + 2*lm2*(1-lm2)*AA!Eltseq(np);
X2 := Y2 + mu2*AA!Eltseq(u3) + 1/2*( lm2^2*(1-lm2^2)/4 + (1+2*lm2)*mu2)*AA!Eltseq(u4);

assert IsIdempotent(X1);
assert IsIdempotent(X2);

// Inner product between any two 
assert InnerProduct(X1*ChangeRing(frob, KK), X1) eq 1;
assert InnerProduct(X1*ChangeRing(frob, KK), X2) eq 1;




// We know the form of the axis a_n.
// When does X equal a_n?

P<n,s,t> := PolynomialRing(Rationals(), 3);

eq1 := 1/24*(n-1)*(n-2)*(n-3)*(n-4) - 1/8*(-s*(s^3-5*s-4) + 4*(2*s+3)*t);
eq2 := -1/6*n*(n-2)*(n-3)*(n-4) - 1/2*(s^2*(s^2-3) -2*(4*s+5)*t + 2);
eq3 := 1/4*n*(n-1)*(n-3)*(n-4) - 1/4*(-s*(3*s^3-5*s +2) +24*(s+1)*t);
eq4 := -1/6*n*(n-1)*(n-2)*(n-4) - 1/2*(-s^2*(1-s^2) - 2*(4*s+3)*t);
eq5 := 1/24*n*(n-1)*(n-2)*(n-3) - 1/8*(s^2*(1-s^2) + 4*(2*s+1)*t);

eq1 *:= 24;
eq2 *:= -6;
eq3 *:= 4;
eq4 *:= -6;
eq5 *:= 24;

assert n*eq1 - (n-1)*eq2 eq n*(-6*(s*(s+2) + t+1)) + 3*s^2*(s^2-3) -6*(4*s+5)*t +6;
assert (n-1)*eq2 - (n-2)*eq3 eq n*(2*(-s*(2*s+1) -3*(t-1))) + s*(3*s^3-s+4) -6*(4*s+3)*t -6;
assert (n-2)*eq3 - (n-3)*eq4 eq n*(-2*(s*(s-1)+3*t)) + s*(3*s^3 +s-4) -6*(4*s+1)*t;
assert (n-3)*eq4 - (n-4)*eq5 eq n*(-6*t) + 3*( s^2*(s^2-1) - 2*(4*s-1)*t);

// Now eliminate the n using the last equation each time

e1 := 3*( s^2*(s^2-1) - 2*(4*s-1)*t)*(-6*(s*(s+2) + t+1)) +6*t*(3*s^2*(s^2-3) -6*(4*s+5)*t +6);
e2 := 3*( s^2*(s^2-1) - 2*(4*s-1)*t)*(2*(-s*(2*s+1) -3*(t-1))) +6*t*(s*(3*s^3-s+4) -6*(4*s+3)*t -6);
e3 := 3*( s^2*(s^2-1) - 2*(4*s-1)*t)*(-2*(s*(s-1)+3*t)) +6*t*( s*(3*s^3 +s-4) -6*(4*s+1)*t);

e1 *:= 1/18;
e2 *:= 1/6;
e3 *:= 1/6;

assert e3-e1 eq s*( s*(3*s^3 + s^2 - 3*s - 1) - 6*(3*s+1)*t);
assert  e2-2*e3 eq s*( s*(-3*s^3 + 3*s^2 + 3*s - 3) + 18*(s-1)*t);

// So either s = 0
assert Evaluate(e1, 2,0) eq -12*t^2;
// so t = 0 and hence x = 0

// So can divide the two equations above through by s
d1 := (e3-e1)/s;
d2 := (e2-2*e3)/s;

assert d1 + d2 eq 4*( s*(s^2-1) -6*t);

// so t = 1/6*s*(s^2-1) is the solution

assert Evaluate(e1, 3, 1/6*s*(s^2-1)) eq 0;
assert Evaluate(e2, 3, 1/6*s*(s^2-1)) eq 0;
assert Evaluate(e3, 3, 1/6*s*(s^2-1)) eq 0;

// Find the value for n

eq1n := Evaluate(eq1, 3, 1/6*s*(s^2-1));
eq2n := Evaluate(eq2, 3, 1/6*s*(s^2-1));
eq3n := Evaluate(eq3, 3, 1/6*s*(s^2-1));
eq4n := Evaluate(eq4, 3, 1/6*s*(s^2-1));
eq5n := Evaluate(eq5, 3, 1/6*s*(s^2-1));

assert eq1n - eq5n eq 4*(-n^3 + 6*n^2 - 11*n - s^3 - 3*s^2 - 2*s + 6);
assert eq2n - eq5n eq 3*(-n^3 + 5*n^2 - 6*n - s^3 - 2*s^2 + s + 2);
assert eq3n - eq5n eq 2*(-n^3 + 4*n^2 - 3*n - s^3 - s^2 + 2*s);
assert eq4n - eq5n eq -n^3 + 3*n^2 - 2*n - s^3 + s;

d15 := (eq1n - eq5n)/4;
d25 := (eq2n - eq5n)/3;
d35 := (eq3n - eq5n)/2;
d45 := eq4n - eq5n;

assert d15-d45 eq 3*(n^2 - 3*n - s^2 - s + 2);
assert d25-d45 eq 2*(n^2 - 2*n - s^2 + 1);
assert d35-d45 eq n^2 - n - s^2 + s;

d15_45 := (d15-d45)/3;
d25_45 := (d25-d45)/2;
d35_45 := d35-d45;

assert d15_45 - d35_45 eq 2*(-n-s+1);
assert d25_45 - d35_45 eq -n-s+1;

// so n = s+1, t = 1/6*s*(s^2-1) is the solution

// ---------------------------------------------------
//
// Computations for the automorphism group

A, gens, frob := IY5();
F<al> := BaseRing(A);

// We change basis
u1 := A![1,-1,0,0,0,0];
u2 := A![1,-2,1,0,0,0];
u3 := A![1,-3,3,-1,0,0];
u4 := A![1,-4,6,-4,1,0];
z := A.6;

zp := 1/4/al*(u2+4*z);
np := -1/8/al*( (2*al-1)*u2 -4*z);
zzp := zp + 1/8/al*( u3 + (4*al-1)/4/al*u4);
nnp := np - (2*al-1)/16/al*( u3 + (4*al-1)/4/al*u4);

// bas := [ A.1+A.2, u1, zp+ 1/8/al*u3 + (4*al-1)/32/al^2*u4, np -(2*al-1)/2*(1/8/al*u3 + (4*al-1)/32/al^2*u4), u3, u4];
zzp := zp+ 1/8/al*u3 + (4*al-1)/32/al^2*u4;
nnp := np -(2*al-1)/2*(1/8/al*u3 + (4*al-1)/32/al^2*u4);

assert (A.1+A.2)^2 eq 2*(A.1+A.2) + (2*al-1)*zzp + 2*nnp;
assert (A.1+A.2)*u1 eq u1;
assert (A.1+A.2)*zzp eq 2*al*zzp;
assert (A.1+A.2)*nnp eq (2*al-1)/32/al*u4;
assert (A.1+A.2)*u3 eq u3+u4;

assert u1^2 eq -(2*al-1)*zzp - 2*nnp;
assert u1*zzp eq (2*al-1)/8/al*(u3+u4);
assert u1*nnp eq (2*al-1)/8/al*(u3+u4);
assert u1*u3 eq 1/2*u4;

assert zzp^2 eq (al-1)/8/al*u4;
assert zzp*nnp eq 0;
assert zzp*u3 eq 0;

assert nnp^2 eq -(2*al-1)/32/al*u4;
assert nnp*u3 eq 0;

bas := [ A.1+A.2, u1, zp+ 1/8/al*u3 + (4*al-1)/32/al^2*u4, np -(2*al-1)/2*(1/8/al*u3 + (4*al-1)/32/al^2*u4), u3, u4];
AA := ChangeBasis(A, bas);

P<gm, dl> := PolynomialRing(F, 13);

g := VerticalJoin(
       HorizontalJoin( Matrix([[1, gm, 1/2*(gm^2+dl^2-1), -(gm^2+dl^2-1)],
             [0, dl, gm*dl, -2*gm*dl],
             [0,   0, dl^2, 0  ],
             [0,   0,   0, dl^2]]),
             Matrix(4,2,[P.i : i in [3..10]])),
       Matrix([[0,0,0,0,P.11, P.12],[0,0,0,0,0,P.13]]));
             
AA := ChangeRing(AA, P);

autrelation := function(x,y)
  return {@ P | v : v in Eltseq(AA!(Vector((x*y))*g) - (x*g)*(y*g)) | v ne 0@};
end function;

relations := &join { autrelation(AA.i, AA.j) : j in [1..i], i in [1..6]};
 
assert (AA.1*AA.5)*g - (AA.1*g)*(AA.5*g) eq (-(1+gm/2)*P.11 +P.12 + P.13)*AA.6;
assert (AA.2*AA.5)*g - (AA.2*g)*(AA.5*g) eq 1/2*(-dl*P.11 + P.13)*AA.6;

I;
assert (AA.1*AA.4)*g - (AA.1*g)*(AA.4*g) eq ((-2*al + 1)/(16*al)*gm*dl^2 - P.9)*AA.5 + 
           + ( -(1+ 1/2*gm)*P.9 + (2*al-1)/32/al*( P.13 - dl^2*( gm*(gm +2) + dl^2)))*AA.6;

assert (AA.2*AA.4)*g - (AA.2*g)*(AA.4*g) eq (2*al-1)/16/al*(P.11-dl^3)*AA.5 + 
           (-1/2*dl*P.9 + (2*al - 1)/(16*al)*(P.12+P.13 - dl^3*(gm+1)))*AA.6;
assert (AA.3*AA.4)*g - (AA.3*g)*(AA.4*g) eq 0;
assert (AA.4^2)*g - (AA.4*g)*(AA.4*g) eq (2*al - 1)/(32*al)*(dl^4 - P.13)*AA.6;


autg := function(gm,dl,et, th)
  g26 := dl/2*et + (gm/2+1)*th -(al-1)/16/al*gm*dl -gm*dl/16*(gm^2+dl^2);
  g46 := dl^2/64/al^2*((1-dl^2)*(2*al-1)*(al-1) + al*gm*(2*al*(gm-4) + gm+4))-dl/2*th;
  g16 := -g46 -(2*al-1)*dl^2/64/al^2*((1-dl^2)*(1-al) + (gm+4)*al*gm) + (gm/2+1)*et + (3*al-2)/64/al -(al-1)/32/al*(gm^2+dl^2) -1/64*(gm^2+dl^2)^2;
  
  return Matrix([[1, gm, 1/2*(gm^2+dl^2-1), -(gm^2+dl^2-1), et, g16 ],
             [0, dl, gm*dl, -2*gm*dl, th, g26],
             [0,   0, dl^2, 0  , gm*dl^2/8/al, dl^2/32/al^2*((1-dl^2)*(1-al) + (gm+4)*al*gm)],
             [0,   0,   0, dl^2, -(2*al-1)/16/al*gm*dl^2, g46],
             [0, 0, 0, 0, dl^3, dl^3*(1+gm/2-dl)],
             [0, 0, 0, 0, 0, dl^4]]);
end function;





bas := [ A.1+A.2, u1, zp, np, u3, u4];

AA := ChangeBasis(A, bas);

P<gm, dl> := PolynomialRing(F, 13);

g := VerticalJoin(
       HorizontalJoin( Matrix([[1, gm, 1/2*(gm^2+dl^2-1), -(gm^2+dl^2-1)],
             [0, dl, gm*dl, -2*gm*dl],
             [0,   0, dl^2, 0  ],
             [0,   0,   0, dl^2]]),
             Matrix(4,2,[P.i : i in [3..10]])),
       Matrix([[0,0,0,0,P.11, P.12],[0,0,0,0,0,P.13]]));
             
AA := ChangeRing(AA, P);

autrelation := function(x,y)
  return {@ P | v : v in Eltseq(AA!(Vector((x*y))*g) - (x*g)*(y*g)) | v ne 0@};
end function;

relations := &join { autrelation(AA.i, AA.j) : j in [1..i], i in [1..6]};


(-al + 1)*dl^2*(gm^2 + dl^2)
+ (4*al - 3)*dl^2*(dl^2-gm)
+ (-3*al + 2)*dl^2 
+ (2*al - 1)*dl^3*(2+gm-2*dl) 
- (gm+2)*dl^2*(1+gm-dl)
+ 32*al^2*P.8 

32*al^2*P.8 
+ dl^2*( (-al + 1)*(gm^2 + dl^2)
+ (4*al - 3)*(dl^2-gm)
+ (-3*al + 2)
+ (2*al - 1)*dl*(2+gm-2*dl) 
- (gm+2)*(1+gm-dl))

P.8 
+ dl^2/32/al^2*( 


(-al + 1)*(gm^2 + dl^2)
+ (4*al - 3)*(dl^2-gm)
+ (-3*al + 2)
+ (2*al - 1)*dl*(2+gm-2*dl) 
- (gm+2)*(1+gm-dl))

1/32*((gm^2 + dl^2)^2 + 4*gm^2*dl^2 + 4*gm^3 + 2*gm^2 + 12*gm*dl^2  - 4*gm  + 2*dl^2 -3)
 - dl*P.5 - (gm+2)*P.3 + 2*P.4


1/16*dl*(gm^3 + 3*gm^2 + gm*dl^2 + gm  + dl^2 - 1)
 -1/2*dl*et + P.6- (gm/2+1)*th

  g26 := (gm/2+1)*th + dl/2*et -dl/16*(gm^3 + 3*gm^2 + gm*dl^2 + gm + dl^2 - 1);

1/4*gm*dl^2*(gm/2+1)
 - dl*th + (-2*al + 1)*dl^2/32/al*(gm-dl+3)*(gm-dl+1) - 2*P.10
 
g46 := -dl/2*th + (1-2*al)*dl^2/64/al*(gm-dl+3)*(gm-dl+1) + 1/8*gm*dl^2*(gm/2+1);
 
autg := function(gm, dl, et, th)
  g16 := (gm/2+1)*et + dl/2*th -1/64*((gm^2+dl^2)^2 + 4*gm^2*dl^2 + 4*gm^3 + 2*gm^2 + 12*gm*dl^2 -4*gm+2*dl^2-3);
  g26 := (gm/2+1)*th + dl/2*et -dl/16*(gm^3 +3*gm^2+gm*dl^2+gm+dl^2-1);
  g46 := -dl/2*th + (1-2*al)*dl^2/64/al*(gm-dl+3)*(gm-dl+1) + 1/8*gm*dl^2*(gm/2+1);
  
  return Matrix([[1, gm, 1/2*(gm^2+dl^2-1), -(gm^2+dl^2-1), et, g16 ],
             [0, dl, gm*dl, -2*gm*dl, th, g26],
             [0,   0, dl^2, 0  , dl^2/8/al*(1+gm-dl), dl^2/32/al*(gm-dl+3)*(gm-dl+1)],
             [0,   0,   0, dl^2, (1-2*al)/16/al*dl^2*(1+gm-dl), g46],
             [0, 0, 0, 0, dl^3, dl^3*(1+gm/2-dl)],
             [0, 0, 0, 0, 0, dl^4]]);
end function;

FF<gm1,dl1,et1,th1,gm2,dl2,et2,th2> := FunctionField(F,8);

AFF := ChangeRing(ChangeBasis(A,bas), FF);

assert autg(0,1,et1,th1)*autg(0,1,et2,th2) eq autg(0,1,et1+et2,th1+th2);

g1 := autg(gm1,dl1,et1,th1);
n := autg(0,1,et2,th2);

// so n spans a normal subgroup
assert g1^-1*n*g1 eq autg(0,1,dl1^2*(dl1*et2 -gm1*th2), dl1^2*th2);


assert AA.1^2 eq 2*AA.1 + (2*al-1)*AA.3 + 2*AA.4;
assert AA.1*AA.2 eq AA.2;
assert AA.1*AA.3 eq 2*al*AA.3 + (2*al-1)/8/al*AA.5 + (4*al-3)/16/al*AA.6;
assert AA.1*AA.4 eq (2*al - 1)*( 1/(16*al)*AA.5 + 3/(32*al)*AA.6);
assert AA.1*AA.5 eq AA.5+AA.6;


assert AA.2*AA.2 eq -(2*al-1)*AA.3 -2*AA.4;
assert AA.2*AA.3 eq (2*al-1)/8/al*AA.5 + (4*al-3)/16/al*AA.6;
assert AA.2*AA.4 eq (2*al - 1)*( 1/(16*al)*AA.5 + 3/(32*al)*AA.6);


assert (A.1+A.2)^2 eq 2*(A.1+A.2) + (2*al-1)*zp + 2*np;
assert (A.1+A.2)*u1 eq u1;
assert (A.1+A.2)*zp eq (16*al - 5)/(16*al)*u4;


assert u1^2 eq -(2*al-1)*zp -2*np;












