/*

Check the algebras which normally have the infinite axet

*/
AttachSpec("../2-gen Monster.spec");
AttachSpec("../../AxialTools/AxialTools.spec");

Attach("../Yabe_algebras.m");

QQ := Rationals();
ZZ := Integers();
// =========================================================
//
// IY3
//
// =========================================================






// Check isomorphisms
// mu = -1 gives 3 axes
M := Matrix(Rationals(),2,2,[1,-1/2,-1/2,1]);
A, frob := SplitSpinFactor(M);
F<al> := BaseRing(A);

a1 := 1/2*(A.1+al*A.3+(al+1)*A.4);
a2 := 1/2*(A.2+al*A.3+(al+1)*A.4);

t1 := MiyamotoInvolution(a1,1/2);
t2 := MiyamotoInvolution(a2,1/2);
assert Order(t1*t2) eq 3;

a3 := a1*t2;

so, id := HasOne(A);
assert so;
assert id eq A.3+A.4;

lm := -al*(3*al^2+3/2*al-3/2)/(4*(2*al-1));
assert lm eq -3/8*al*(al+1);
z := lm*id;

bas := [a1,a2,a3,z];
assert forall{v : v in bas | z*v eq lm*v};

assert a1*a2 eq (al+1/2)/2*(a1+a2) + (al-1/2)/2*a3 + z;

// So IY_3(al,1/2,-1/2) \cong 3A(al, 1/2)


// Look at char 3
M := Matrix(GF(3),2,2,[1,1,1,1]);
A, frob := SplitSpinFactor(M);
F<al> := BaseRing(A);

a1 := 1/2*(A.1+al*A.3+(al+1)*A.4);
a2 := 1/2*(A.2+al*A.3+(al+1)*A.4);

t1 := MiyamotoInvolution(a1,1/2);
t2 := MiyamotoInvolution(a2,1/2);
assert Order(t1*t2) eq 3;

a3 := a1*t2;
so, id := HasOne(A);
assert so;
assert id eq A.3+A.4;

// So this is not isomorphic to 3A(al,1/2) in char 3 as 3A has no id and instead has an annihilator.
// The quotient 3A/Ann \cong 3C(-1) in char 3.

assert Dimension(Nullspace(frob)) eq 1;
R := ideal<A|[ A!v : v in Basis(Nullspace(frob))]>;
assert A.1-A.2 in R;

B,quo := quo<A|R>;
// We are quotienting by difference of axes, so all axes are equal in the quotient.
assert a1-a2 in R and a1-a3 in R;


// There are additional axes in the quotient
z1 := A.3;
assert HasJordanFusionLaw(z1@quo: fusion_value:=al);
d := 1/2*(-A.1 + al*A.3+(al+1)*A.4);

assert HasJordanFusionLaw(d@quo: fusion_value:=al);
assert a1*z1- al/2*(a1+z1-d) in R;
// so quotient is 3C(al), but the image of our generating axes only gives us 1 axis, not 2.




// =========================================================
//
// IY5
//
// =========================================================
A, gens, frob := IY5();
F<al> := BaseRing(A);

assert not HasOne(A);

assert HasMonsterFusionLaw(A.3);
u4 := A.1-4*A.2+6*A.3-4*A.4+A.5;
v0_2 := 2*A.3 - (A.2+A.4) +2/(al-1/2)*A.6;

val := 2*A.3 - (A.2+A.4) - 4*A.6;

vbt_1 := A.1-A.5;
vbt_2 := A.2-A.4;

assert A.3*u4 eq 0;
assert A.3*v0_2 eq 0;

assert A.3*val eq al*val;

assert A.3*vbt_1 eq 1/2*vbt_1;
assert A.3*vbt_2 eq 1/2*vbt_2;


// Subalgebras??
// No axial subalgebras - show that a_0 and a_i generate A

// No ideals containing an axis
assert forall{i : i in [2..5] | frob[1,i] eq 1};

R := ideal<A | [A!Vector(v) : v in Basis(NullSpace(frob))]>;

z := A.6;
assert z in R;
assert forall{i : i in [1..4] | A.i - A.(i+1) in R};

// Get the group
t1 := MiyamotoInvolution(A.1);
t2 := MiyamotoInvolution(A.2);

f := Matrix(F,[[1,-5,10,-10,5, 0],
              [0, 0, 0, 0, 1, 0],
              [0, 0, 0, 1, 0, 0],
              [0, 0, 1, 0, 0, 0],
              [0, 1, 0, 0, 0, 0],
              [0, 0, 0, 0, 0, 1]]);

assert forall{<i,j> : j in [i..6], i in [1..6] | (A.i*f)*(A.j*f) eq (A.i*A.j)*f};

Miy := sub<GL(6,F)|t1,t2>;

G := sub<GL(6,F) | t1,t2,f>;

// First examine the G-module structure of R
// In this case the Miy group is D_\infty, or if the field has char p, then it is D_2p (D_2*9 if char F eq 3)
// Note that either the Miy is infinite, or we are in modular rep theory.

// Clear z is fixed by Miy
// This has a complement N4

M := GModule(Miy);
N1 := sub<M | M.1-M.2>;
assert Dimension(N1) eq 4;

// So the G-module structure of the radical is 1+4, where <z> \oplus N4

// N1 is a uniserial module

// take differences: M.1-M.2 - (M.2-M.3) = M.1-2*M.2+M.3
N2 := sub<M | M![1,-2,1,0,0,0]>;
assert Dimension(N2) eq 3;
// take differences: M.1-2*M.2+M.3 - (M.1-2*M.2+M.3) = M.1-3*M.2+3*M.3-M.4
N3 := sub<M | M![1,-3,3,-1,0,0]>;
assert Dimension(N3) eq 2;
// take differences: M.1-3*M.2+3*M.3-M.4 - (M.2-3*M.3+3*M.4-M.5) = M.1-4*M.2+6*M.3-4*M.4+M.5
N4 := sub<M | M![1,-4,6,-4,1,0]>;
assert Dimension(N4) eq 1;
// this is the element u1

// NB Still hold in char 3

// indecomposible modules are generated by z, or lm z + u_k, for some lm.
// So modules are generated by lm z + u_k, or are <z>, <z, u_k>, or <u_k>

// Let u_k = \sum{i=0}^k (-1)^i \binom{k}{i} a_i
u1 := A![1,-1,0,0,0,0];
u2 := A![1,-2,1,0,0,0];
u3 := A![1,-3,3,-1,0,0];
u4 := A![1,-4,6,-4,1,0];
z := A.6;

// These span R and so are a basis for R
assert forall{ x : x in [z,u1,u2,u3,u4] | x in R};

// Now we record the multiplications we will need.
// First for u1
Ann := Annihilator(A);
assert Dimension(Ann) eq 1;
assert u4 in Ann;

assert z^2 eq (2*al-3)*(2*al-1)/32*u4;
assert A.2*z eq (2*al-1)/8*( u2 + 4*z );

assert A.3*u3 eq -1/4*u4 + 1/2*u3;
assert A.4*u3 eq -3/4*u4 + 1/2*u3;
assert A.5*u3 eq -5/4*u4 + 1/2*u3;
assert A.6*u3 eq 0;

assert A.2*u2 eq           1/2*u2 + 2*z;
assert A.3*u2 eq -1/4*u4 + 1/2*u2 + 2*z;
assert A.4*u2 eq     -u4 + 1/2*u2 + 2*z;
assert A.5*u2 eq -9/4*u4 + 1/2*u2 + 2*z;
assert A.6*u2 eq 1/8*(2*al-1)*u4;

assert A.2*u1 eq           1/2*u1 + z;
assert A.3*u1 eq -1/4*u4 + 1/2*u1 + 3*z;
assert A.4*u1 eq -5/4*u4 + 1/2*u1+ 5*z;
assert A.5*u1 eq -7/2*u4 + 1/2*u1 + 7*z;
assert A.6*u1 eq 1/8*(2*al-1)*(u3+u4);

// In the basis A.2, u1,u2,u3,u4,z
assert A.2*z eq (2*al-1)/8*( u2 + 4*z );
assert z^2 eq (2*al-3)*(2*al-1)/32*u4;

assert A.2*u3 eq 1/4*(2*u3 + u4);
assert u1*u3 eq 1/2*u4;
assert u2*u3 eq 0;
assert u3*u3 eq 0;
assert z*u3 eq 0;

assert A.2*u2 eq 1/2*(u2 + 4*z);
assert u1*u2 eq -1/4*u4;
assert u2*u2 eq -1/2*u4;
assert z*u2 eq (2*al-1)/8*u4;

assert A.2*u1 eq 1/2*(u1 + 2*z);
assert u1*u1 eq -2*z;
assert z*u1 eq (2*al-1)/8*(u3+u4);


// Already know that Ann eq <u4>
// Check the ideals generated by <ui>

// By above, <u3> is a 2-dim ideal, spanned by u3 and u4.
I3 := ideal<A|u3>;
assert Dimension(I3) eq 2;
assert u4 in I3 and u3 in I3;

// By above, z in <u2>
I2 := ideal<A|u2>;
assert Dimension(I2) eq 4;
assert u4 in I2 and u3 in I2 and u2 in I2 and z in I2;

// By above, z in <u1>
assert ideal<A|u1> eq R;

// From the above, <z> does not generate a 1-dim ideal.
// u4, u3, u2, z in <z> = <z,u2> = <u2>
assert ideal<A|z> eq I2;

// Already seen z in <u1> = R.
// Also from above, <u4, z> = <u4, u2, z> = <u2>
// And similarly <u3, z> = <u3, u2, z> = <u2>

// Now consider ideals generated by lm z + u_k

// For lm z + u1, multiplying by (3A.3-A.2)  implies that u1 + lm(2al-1)z in I
// Hence so we need al = 1, a contradiction.
// So u1 and z in ideal
// So this generates R
// eg
assert ideal<A|u1+z> eq R;

// For lm z + u2, there are two options:
// either lm = 4, so that a_i(u2+4z) gives mu(u2+4z) + some amount of u3 and u4
// or lm = -4/(2al-1), so that a_i(u2+lmz) eq 0 + some amount of u3 and u4
// otherwise I = <u2,z> = <u2> = I2 which is 4-dim
x := u2 + 4*z;
Ix := ideal<A | x>;
assert Dimension(Ix) eq 3;
assert x in Ix and u3 in Ix and u4 in Ix;

y := u2 - 2/(al-1/2)*z;
assert A.2*y eq 0;
Iy := ideal<A | y>;
assert Dimension(Iy) eq 3;
assert y in Iy and u3 in Iy and u4 in Iy;

// for lm z + u3
assert (A.2-A.3)*u3 eq 1/2*u4;
assert (A.2-A.3)*z eq (2*al-1)/8*u3;
// so u_3 in the ideal and hence z is.  So now by above u_2 is
// So we get <u2, z> = <u2> = I2, which is 4 dim
// eg
assert ideal<A|z+u3> eq I2;

// Similarly for lm z + u4
// We get <u4, z>
assert ideal<A|z+u4> eq I2;

// ---------------------------------------------------
// Now investigate the quotients

B4, quo4 := quo<A | Ann>;
assert not HasOne(B4);
assert Dimension(Annihilator(B4)) eq 0;

assert A.1@quo4 eq B4.1 and A.2@quo4 eq B4.2;
assert sub<B4 | B4.1, B4.2> eq B4;
assert HasMonsterFusionLaw(B4.1:fusion_values:=[al,1/2]);
assert Dimension(Eigenspace(B4.1, 0)) eq 1;
assert Dimension(Eigenspace(B4.1, al)) eq 1;
assert Dimension(Eigenspace(B4.1, 1/2)) eq 2;
// This is IY5^x

assert Vector(u3@quo4) in Eigenspace(B4.1, 1/2);

// ---------------------------------------------------
B3, quo3 := quo<A|I3>;
assert not HasOne(B3);
assert Dimension(Annihilator(B3)) eq 1;

// This is a new algebra!!
assert A.1@quo3 eq B3.1 and A.2@quo3 eq B3.2;
assert sub<B3 | B3.1, B3.2> eq B3;
// The fusion law is Monster type, but with gaps.
// 0*0, 0*al, al*al are all empty
assert HasMonsterFusionLaw(B3.1:fusion_values:=[al,1/2]);
assert Dimension(Eigenspace(B3.1, 0)) eq 1;
assert Dimension(Eigenspace(B3.1, al)) eq 1;
assert Dimension(Eigenspace(B3.1, 1/2)) eq 1;
// It is 4-dim and has al in eigenspace

assert y@quo3 in Annihilator(B3);
assert Vector(x@quo3) in Eigenspace(B3.1, al);
// Looking at the fusion law, either of these gives a 1-dim ideal, which matches above analysis.

// ---------------------------------------------------
Bx, quox := quo<A|Ix>;
assert not HasOne(Bx);
assert Dimension(Annihilator(Bx)) eq 1;

assert A.1@quox eq Bx.1 and A.2@quox eq Bx.2;
assert sub<Bx | Bx.1, Bx.2> eq Bx;
assert HasJordanFusionLaw(Bx.1:fusion_value:=1/2);

zz := -(2*al-1)/8/al*y@quox;
assert zz in Annihilator(Bx);

assert Bx.1*Bx.2 eq 1/2*(Bx.1 + Bx.2) + zz;
// So this is \widehat{S}(2)^\circ

// ---------------------------------------------------
By, quoy := quo<A | Iy>;
assert not HasOne(By);
assert Dimension(Annihilator(By)) eq 0;

assert A.1@quoy eq By.1 and A.2@quoy eq By.2;
assert sub<By | By.1, By.2> eq By;
assert HasMonsterFusionLaw(By.1:fusion_values:=[al,1/2]);
assert Dimension(Eigenspace(By.1, 0)) eq 0;
assert Dimension(Eigenspace(By.1, al)) eq 1;
assert Dimension(Eigenspace(By.1, 1/2)) eq 1;
// Fusion law has gaps with al*al and al*1/2 empty

u := (x/2/al)@quoy;
// u is the common al eigenspace
assert forall{ i : i in [1..3] | By.i*u eq al*u};
// This is a 1-dim ideal, which fits the above picture

w := By.1*By.2;
assert w*w eq (1/4-al)*(By.1+By.2) + (2*al+1/2)*w;
// This is Maddy Whybrow's example in fusion law d in
// Graded 2-generated axial algebras, https://arxiv.org/abs/2005.03577
// Also type (a) with x = 1


// -----------------------------------------------------
B2, quo2 := quo<A | I2>;
assert Dimension(B2) eq 2;
assert A.1@quo2 eq B2.1 and A.2@quo2 eq B2.2;
assert B2.1*B2.2 eq 1/2*(B2.1+B2.2);
// so the quotient is S(2)^\circ



// --------------------------------------------------------
//
// idempotents
//
load "Find idempotents.m";

I := IdempotentIdeal(A);
prim := PrimaryDecomposition(A);

assert #prim eq 2;
assert exists(J0){ J : J in prim | Dimension(J) eq 0};

assert exists(J2){ J : J in prim | Dimension(J) eq 2};

// In the ideal of dim 0, there is only 0
assert VarietySizeOverAlgebraicClosure(J0) eq 1;
assert Variety(J0) eq [<0,0,0,0,0,0>];











